"""
skill_code_generator.py
====================
Generates a skill *scaffold* from a `SkillSpec` - function signatures,
docstrings, a `requests`-based HTTP call stubbed in for each declared
endpoint, and a standard `SKILL_METADATA` block that
`skill_validator.py` and `auto_deployer.py` both key off of.

This is template-based generation, not free-form code synthesis: the
output is always the same handful of well-understood shapes (one
function per endpoint, one class wrapper) with names/params filled
in. That's a deliberate ceiling - anything the templates can't
express (custom auth flows, non-REST protocols, side-effecting logic)
is left as a `# TODO(human):` marker for you to fill in by hand,
rather than the generator guessing at behavior it can't verify.

Pure standard library.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional

from .api_doc_reader import APIEndpoint

logger = logging.getLogger("ultron.skill_code_generator")

_NAME_RE = re.compile(r"[^a-zA-Z0-9_]+")


@dataclass
class SkillSpec:
    skill_name: str
    description: str
    base_url: str
    endpoints: List[APIEndpoint] = field(default_factory=list)
    auth_env_var: Optional[str] = None  # e.g. "WIDGETCO_API_KEY" - never hardcode secrets
    version: str = "0.1.0"


def _to_function_name(method: str, path: str) -> str:
    cleaned = _NAME_RE.sub("_", path.strip("/")).strip("_").lower()
    return f"{method.lower()}_{cleaned}" if cleaned else method.lower()


class SkillCodeGenerator:
    """Renders a `SkillSpec` into a single importable Python module string."""

    def generate(self, spec: SkillSpec) -> str:
        class_name = "".join(w.capitalize() for w in _NAME_RE.sub(" ", spec.skill_name).split())
        methods_code = (
            "\n\n".join(self._render_endpoint(ep) for ep in spec.endpoints)
            or "    # TODO(human): no endpoints were provided to the generator - add methods here.\n    pass"
        )

        auth_lines = ""
        if spec.auth_env_var:
            auth_lines = (
                f'        api_key = os.environ.get("{spec.auth_env_var}")\n'
                f"        if not api_key:\n"
                f'            raise RuntimeError("Set the {spec.auth_env_var} environment variable "'
                f'"before using this skill.")\n'
                f'        self._headers = {{"Authorization": f"Bearer {{api_key}}"}}\n'
            )
        else:
            auth_lines = "        self._headers = {}\n"

        module = f'''"""
Auto-generated by SKILL_CREATOR.skill_code_generator on {datetime.now().isoformat()}.
Skill: {spec.skill_name}
{spec.description}

Generated scaffolds only cover request shape (method, path, params).
Anything marked TODO(human) needs a person to fill in before this
skill should be deployed - review with skill_validator before use.
"""

import os
import requests

SKILL_METADATA = {{
    "name": "{spec.skill_name}",
    "version": "{spec.version}",
    "description": {spec.description!r},
    "generated": True,
    "generated_at": "{datetime.now().isoformat()}",
}}


class {class_name}Skill:
    """Generated wrapper around {spec.base_url}"""

    BASE_URL = "{spec.base_url}"

    def __init__(self):
{auth_lines}
{methods_code}
'''
        return module

    def _render_endpoint(self, ep: APIEndpoint) -> str:
        fn_name = _to_function_name(ep.method, ep.path)
        params = [p["name"] for p in ep.parameters]
        py_params = ", ".join(["self"] + [f"{p}" for p in params]) if params else "self"

        # Build path with .format(**kwargs) for path params
        path_params = [p["name"] for p in ep.parameters if p.get("in") == "path"]
        query_params = [p["name"] for p in ep.parameters if p.get("in") == "query"]

        path_expr = ep.path
        for p in path_params:
            path_expr = path_expr.replace("{" + p + "}", "{" + p + "}")

        query_dict = "{" + ", ".join(f'"{p}": {p}' for p in query_params) + "}" if query_params else "{}"

        summary = ep.summary or f"{ep.method} {ep.path}"

        body = f'''    def {fn_name}({py_params}):
        """{summary}"""
        url = self.BASE_URL + f"{path_expr}"
        # TODO(human): confirm timeout/retry policy fits this API before deploying.
        response = requests.request(
            "{ep.method}", url, headers=self._headers,
            params={query_dict}, timeout=10,
        )
        response.raise_for_status()
        return response.json()
'''
        return body


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    spec = SkillSpec(
        skill_name="widget_co",
        description="Fetch and list widgets from WidgetCo's API.",
        base_url="https://api.widgetco.example.com",
        endpoints=[
            APIEndpoint(
                path="/v1/widgets/{id}",
                method="GET",
                summary="Fetch a widget by id",
                parameters=[{"name": "id", "in": "path", "required": True, "type": "string"}],
            ),
        ],
        auth_env_var="WIDGETCO_API_KEY",
    )
    print(SkillCodeGenerator().generate(spec))
