"""
Phase 6 app-automation tool registry (auto-generated)
=========================================================
Wires every apps/* automation class into the AI tool-calling loop,
mirroring ai/new_skills_tools.py's pattern: lazy singletons + a flat
APPS_TOOLS / APPS_DIRECT_HANDLERS pair merged at the bottom of
ai/tools_schema.py and ai/tool_runtime.py.

Generated by scripts/_generate_apps_tools.py - re-run that script
after adding/changing methods on an apps/* class rather than editing
the per-app tool entries below by hand.
"""

from typing import Dict


def _tool(name: str, description: str, properties: dict = None, required: list = None) -> dict:
    """Identical shape to ai/tools_schema.py's _tool() - duplicated on
    purpose (see ai/new_skills_tools.py's docstring for why: avoids a
    circular import since tools_schema.py imports *from* this module)."""
    return {
        "type": "function",
        "function": {
            "name": name,
            "description": description,
            "parameters": {
                "type": "object",
                "properties": properties or {},
                "required": required or [],
            },
        },
    }


def _pick(d: dict, keys: list) -> dict:
    """Filter a raw tool-call args dict down to the keys a method
    accepts, dropping missing/None entries so the method's own
    defaults apply."""
    return {k: d[k] for k in keys if k in d and d[k] is not None}


# ---------------------------------------------------------------------------
# App registry - every apps/* class, keyed by its filename stem. Also used
# by the four generic app_open/app_close/app_focus/app_is_running tools.
# ---------------------------------------------------------------------------
APP_REGISTRY: Dict[str, str] = {
    "brave": "apps.browsers.brave.BraveApp",
    "chrome": "apps.browsers.chrome.ChromeApp",
    "edge": "apps.browsers.edge.EdgeApp",
    "firefox": "apps.browsers.firefox.FirefoxApp",
    "opera": "apps.browsers.opera.OperaApp",
    "access": "apps.office.access.AccessApp",
    "excel": "apps.office.excel.ExcelApp",
    "onenote": "apps.office.onenote.OneNoteApp",
    "outlook": "apps.office.outlook.OutlookApp",
    "powerpoint": "apps.office.powerpoint.PowerPointApp",
    "teams": "apps.office.teams.TeamsApp",
    "word": "apps.office.word.WordApp",
    "discord": "apps.communication.discord.DiscordApp",
    "messenger": "apps.communication.messenger.MessengerApp",
    "signal": "apps.communication.signal.SignalApp",
    "skype": "apps.communication.skype.SkypeApp",
    "slack": "apps.communication.slack.SlackApp",
    "telegram": "apps.communication.telegram.TelegramApp",
    "whatsapp": "apps.communication.whatsapp.WhatsAppApp",
    "itunes": "apps.media.itunes.ITunesApp",
    "spotify": "apps.media.spotify.SpotifyApp",
    "vlc": "apps.media.vlc.VLCApp",
    "windows_media": "apps.media.windows_media.WindowsMediaApp",
    "youtube_music": "apps.media.youtube_music.YouTubeMusicApp",
    "canva": "apps.design.canva.CanvaApp",
    "figma": "apps.design.figma.FigmaApp",
    "gimp": "apps.design.gimp.GimpApp",
    "illustrator": "apps.design.illustrator.IllustratorApp",
    "photoshop": "apps.design.photoshop.PhotoshopApp",
    "docker": "apps.development.docker.DockerApp",
    "git": "apps.development.git.GitApp",
    "postman": "apps.development.postman.PostmanApp",
    "pycharm": "apps.development.pycharm.PyCharmApp",
    "terminal": "apps.development.terminal.TerminalApp",
    "vscode": "apps.development.vscode.VSCodeApp",
    "dropbox": "apps.cloud.dropbox.DropboxApp",
    "google_drive": "apps.cloud.google_drive.GoogleDriveApp",
    "mega": "apps.cloud.mega.MegaApp",
    "onedrive": "apps.cloud.onedrive.OneDriveApp",
    "control_panel": "apps.system.control_panel.ControlPanelApp",
    "device_manager": "apps.system.device_manager.DeviceManagerApp",
    "file_explorer": "apps.system.file_explorer.FileExplorerApp",
    "powershell": "apps.system.powershell.PowerShellApp",
    "registry": "apps.system.registry.RegistryApp",
    "settings": "apps.system.settings.SettingsApp",
    "task_manager": "apps.system.task_manager.TaskManagerApp",
    "calculator": "apps.utilities.calculator.CalculatorApp",
    "notepad": "apps.utilities.notepad.NotepadApp",
    "paint": "apps.utilities.paint.PaintApp",
    "pdf_reader": "apps.utilities.pdf_reader.PDFReaderApp",
    "snipping_tool": "apps.utilities.snipping_tool.SnippingToolApp",
    "sticky_notes": "apps.utilities.sticky_notes.StickyNotesApp",
    "winrar": "apps.utilities.winrar.WinRARApp",
    "antivirus": "apps.security.antivirus.AntivirusApp",
    "bitlocker": "apps.security.bitlocker.BitLockerApp",
    "firewall": "apps.security.firewall.FirewallApp",
    "windows_defender": "apps.security.windows_defender.WindowsDefenderApp",
    "discord_gaming": "apps.gaming.discord_gaming.DiscordGamingApp",
    "epic_games": "apps.gaming.epic_games.EpicGamesApp",
    "steam": "apps.gaming.steam.SteamApp",
    "xbox": "apps.gaming.xbox.XboxApp",
}

_instances: Dict[str, object] = {}


def _get(key: str):
    if key in _instances:
        return _instances[key]
    if key not in APP_REGISTRY:
        raise ValueError(f"Unknown app '{key}'. Known: {sorted(APP_REGISTRY)}")
    module_path, class_name = APP_REGISTRY[key].rsplit(".", 1)
    import importlib

    mod = importlib.import_module(module_path)
    obj = getattr(mod, class_name)()
    _instances[key] = obj
    return obj


# ---------------------------------------------------------------------------
# Generic lifecycle tools (cover BaseApp's open/close/focus/is_running for
# every app via one tool each, instead of duplicating 4 tools x 61 apps).
# ---------------------------------------------------------------------------
APPS_TOOLS = [
    _tool(
        "app_open",
        "Launch an installed desktop/web app by key (see list_available_apps).",
        {"app": {"type": "string", "description": "App key, e.g. 'chrome', 'spotify', 'vscode'"}},
        ["app"],
    ),
    _tool("app_close", "Close a running app by key.", {"app": {"type": "string"}}, ["app"]),
    _tool("app_focus", "Bring an already-open app's window to the foreground.", {"app": {"type": "string"}}, ["app"]),
    _tool("app_is_running", "Check whether an app is currently running.", {"app": {"type": "string"}}, ["app"]),
    _tool("list_available_apps", "List every app automation key Ultron knows, grouped by category."),
    # -- Per-app automations (auto-generated from each class's own methods) --
    # BraveApp (browsers/brave.py)
    _tool(
        "brave_close_all", "Brave (Open URLs, tabs, windows, and private (Tor) windows in Brave.): close all.", {}, []
    ),
    _tool(
        "brave_new_tab",
        "Brave (Open URLs, tabs, windows, and private (Tor) windows in Brave.): new tab.",
        {"url": {"type": "string"}},
        [],
    ),
    _tool(
        "brave_new_window",
        "Brave (Open URLs, tabs, windows, and private (Tor) windows in Brave.): new window.",
        {"url": {"type": "string"}},
        [],
    ),
    _tool(
        "brave_open_private_window",
        "Brave (Open URLs, tabs, windows, and private (Tor) windows in Brave.): open private window.",
        {"url": {"type": "string"}},
        [],
    ),
    _tool(
        "brave_open_tor_window",
        "Brave (Open URLs, tabs, windows, and private (Tor) windows in Brave.): open tor window.",
        {"url": {"type": "string"}},
        [],
    ),
    _tool(
        "brave_open_url",
        "Brave (Open URLs, tabs, windows, and private (Tor) windows in Brave.): open url.",
        {
            "url": {"type": "string"},
            "private": {"type": "boolean"},
            "tor": {"type": "boolean"},
            "new_window": {"type": "boolean"},
        },
        ["url"],
    ),
    _tool(
        "brave_search",
        "Brave (Open URLs, tabs, windows, and private (Tor) windows in Brave.): search.",
        {"query": {"type": "string"}},
        ["query"],
    ),
    # ChromeApp (browsers/chrome.py)
    _tool("chrome_bookmark_current_page", "Chrome: Ctrl+D on whatever tab is currently focused in Chrome.", {}, []),
    _tool(
        "chrome_close_all", "Chrome (Open URLs, tabs, windows, and incognito sessions in Chrome.): close all.", {}, []
    ),
    _tool("chrome_close_tab", "Chrome: Close the current tab (requires Chrome to be the focused window).", {}, []),
    _tool(
        "chrome_new_tab",
        "Chrome: Open url (or a blank tab) in the already-running Chrome window.",
        {"url": {"type": "string"}},
        [],
    ),
    _tool(
        "chrome_new_window",
        "Chrome (Open URLs, tabs, windows, and incognito sessions in Chrome.): new window.",
        {"url": {"type": "string"}},
        [],
    ),
    _tool(
        "chrome_open_incognito",
        "Chrome (Open URLs, tabs, windows, and incognito sessions in Chrome.): open incognito.",
        {"url": {"type": "string"}},
        [],
    ),
    _tool(
        "chrome_open_url",
        "Chrome (Open URLs, tabs, windows, and incognito sessions in Chrome.): open url.",
        {"url": {"type": "string"}, "incognito": {"type": "boolean"}, "new_window": {"type": "boolean"}},
        ["url"],
    ),
    _tool(
        "chrome_search",
        "Chrome (Open URLs, tabs, windows, and incognito sessions in Chrome.): search.",
        {"query": {"type": "string"}},
        ["query"],
    ),
    # EdgeApp (browsers/edge.py)
    _tool("edge_close_all", "Edge (Open URLs, tabs, windows, and InPrivate sessions in Edge.): close all.", {}, []),
    _tool("edge_close_tab", "Edge (Open URLs, tabs, windows, and InPrivate sessions in Edge.): close tab.", {}, []),
    _tool(
        "edge_new_tab",
        "Edge (Open URLs, tabs, windows, and InPrivate sessions in Edge.): new tab.",
        {"url": {"type": "string"}},
        [],
    ),
    _tool(
        "edge_new_window",
        "Edge (Open URLs, tabs, windows, and InPrivate sessions in Edge.): new window.",
        {"url": {"type": "string"}},
        [],
    ),
    _tool(
        "edge_open_inprivate",
        "Edge (Open URLs, tabs, windows, and InPrivate sessions in Edge.): open inprivate.",
        {"url": {"type": "string"}},
        [],
    ),
    _tool(
        "edge_open_url",
        "Edge (Open URLs, tabs, windows, and InPrivate sessions in Edge.): open url.",
        {"url": {"type": "string"}, "private": {"type": "boolean"}, "new_window": {"type": "boolean"}},
        ["url"],
    ),
    _tool(
        "edge_search",
        "Edge (Open URLs, tabs, windows, and InPrivate sessions in Edge.): search.",
        {"query": {"type": "string"}},
        ["query"],
    ),
    # FirefoxApp (browsers/firefox.py)
    _tool(
        "firefox_close_all", "Firefox (Open URLs, tabs, windows, and private windows in Firefox.): close all.", {}, []
    ),
    _tool(
        "firefox_close_tab", "Firefox (Open URLs, tabs, windows, and private windows in Firefox.): close tab.", {}, []
    ),
    _tool(
        "firefox_new_tab",
        "Firefox (Open URLs, tabs, windows, and private windows in Firefox.): new tab.",
        {"url": {"type": "string"}},
        [],
    ),
    _tool(
        "firefox_new_window",
        "Firefox (Open URLs, tabs, windows, and private windows in Firefox.): new window.",
        {"url": {"type": "string"}},
        [],
    ),
    _tool(
        "firefox_open_private_window",
        "Firefox (Open URLs, tabs, windows, and private windows in Firefox.): open private window.",
        {"url": {"type": "string"}},
        [],
    ),
    _tool(
        "firefox_open_url",
        "Firefox (Open URLs, tabs, windows, and private windows in Firefox.): open url.",
        {"url": {"type": "string"}, "private": {"type": "boolean"}, "new_window": {"type": "boolean"}},
        ["url"],
    ),
    _tool(
        "firefox_search",
        "Firefox (Open URLs, tabs, windows, and private windows in Firefox.): search.",
        {"query": {"type": "string"}},
        ["query"],
    ),
    # OperaApp (browsers/opera.py)
    _tool("opera_close_all", "Opera (Open URLs, tabs, windows, and private windows in Opera.): close all.", {}, []),
    _tool(
        "opera_new_tab",
        "Opera (Open URLs, tabs, windows, and private windows in Opera.): new tab.",
        {"url": {"type": "string"}},
        [],
    ),
    _tool(
        "opera_new_window",
        "Opera (Open URLs, tabs, windows, and private windows in Opera.): new window.",
        {"url": {"type": "string"}},
        [],
    ),
    _tool(
        "opera_open_private_window",
        "Opera (Open URLs, tabs, windows, and private windows in Opera.): open private window.",
        {"url": {"type": "string"}},
        [],
    ),
    _tool(
        "opera_open_url",
        "Opera (Open URLs, tabs, windows, and private windows in Opera.): open url.",
        {"url": {"type": "string"}, "private": {"type": "boolean"}, "new_window": {"type": "boolean"}},
        ["url"],
    ),
    _tool(
        "opera_search",
        "Opera (Open URLs, tabs, windows, and private windows in Opera.): search.",
        {"query": {"type": "string"}},
        ["query"],
    ),
    # AccessApp (office/access.py)
    _tool("access_new_database", "Access (Open and create Access .accdb databases.): new database.", {}, []),
    _tool(
        "access_open_database",
        "Access (Open and create Access .accdb databases.): open database.",
        {"path": {"type": "string"}},
        ["path"],
    ),
    # ExcelApp (office/excel.py)
    _tool(
        "excel_close_workbook",
        "Excel (Open, edit, save, and print .xlsx files via Microsoft Excel.): close workbook.",
        {},
        [],
    ),
    _tool(
        "excel_new_sheet", "Excel (Open, edit, save, and print .xlsx files via Microsoft Excel.): new sheet.", {}, []
    ),
    _tool(
        "excel_new_workbook",
        "Excel (Open, edit, save, and print .xlsx files via Microsoft Excel.): new workbook.",
        {},
        [],
    ),
    _tool(
        "excel_open_file",
        "Excel (Open, edit, save, and print .xlsx files via Microsoft Excel.): open file.",
        {"path": {"type": "string"}},
        ["path"],
    ),
    _tool(
        "excel_print_workbook",
        "Excel (Open, edit, save, and print .xlsx files via Microsoft Excel.): print workbook.",
        {},
        [],
    ),
    _tool("excel_save", "Excel (Open, edit, save, and print .xlsx files via Microsoft Excel.): save.", {}, []),
    # OneNoteApp (office/onenote.py)
    _tool(
        "onenote_new_page",
        "OneNote (Open OneNote and create pages/notes.): new page.",
        {"title": {"type": "string"}},
        [],
    ),
    _tool(
        "onenote_quick_note",
        "OneNote: Windows key + N opens OneNote's Quick Note panel directly.",
        {"text": {"type": "string"}},
        ["text"],
    ),
    # OutlookApp (office/outlook.py)
    _tool(
        "outlook_compose_email",
        "Outlook (Open Outlook, compose mail, and jump to the calendar/inbox.): compose email.",
        {"to": {"type": "string"}, "subject": {"type": "string"}, "body": {"type": "string"}, "cc": {"type": "array"}},
        ["to"],
    ),
    _tool(
        "outlook_new_meeting",
        "Outlook (Open Outlook, compose mail, and jump to the calendar/inbox.): new meeting.",
        {},
        [],
    ),
    _tool(
        "outlook_open_calendar",
        "Outlook (Open Outlook, compose mail, and jump to the calendar/inbox.): open calendar.",
        {},
        [],
    ),
    _tool(
        "outlook_open_inbox",
        "Outlook (Open Outlook, compose mail, and jump to the calendar/inbox.): open inbox.",
        {},
        [],
    ),
    # PowerPointApp (office/powerpoint.py)
    _tool(
        "powerpoint_end_slideshow",
        "PowerPoint (Open, present, save, and print .pptx files via PowerPoint.): end slideshow.",
        {},
        [],
    ),
    _tool(
        "powerpoint_new_presentation",
        "PowerPoint (Open, present, save, and print .pptx files via PowerPoint.): new presentation.",
        {},
        [],
    ),
    _tool(
        "powerpoint_next_slide",
        "PowerPoint (Open, present, save, and print .pptx files via PowerPoint.): next slide.",
        {},
        [],
    ),
    _tool(
        "powerpoint_open_file",
        "PowerPoint (Open, present, save, and print .pptx files via PowerPoint.): open file.",
        {"path": {"type": "string"}},
        ["path"],
    ),
    _tool(
        "powerpoint_previous_slide",
        "PowerPoint (Open, present, save, and print .pptx files via PowerPoint.): previous slide.",
        {},
        [],
    ),
    _tool("powerpoint_save", "PowerPoint (Open, present, save, and print .pptx files via PowerPoint.): save.", {}, []),
    _tool(
        "powerpoint_start_slideshow",
        "PowerPoint (Open, present, save, and print .pptx files via PowerPoint.): start slideshow.",
        {},
        [],
    ),
    # TeamsApp (office/teams.py)
    _tool(
        "teams_join_meeting",
        "Teams (Open Teams, jump to a chat, or start/join a meeting.): join meeting.",
        {"meeting_url": {"type": "string"}},
        ["meeting_url"],
    ),
    _tool(
        "teams_open_chat",
        "Teams (Open Teams, jump to a chat, or start/join a meeting.): open chat.",
        {"email": {"type": "string"}},
        ["email"],
    ),
    _tool(
        "teams_start_call",
        "Teams (Open Teams, jump to a chat, or start/join a meeting.): start call.",
        {"email": {"type": "string"}, "video": {"type": "boolean"}},
        ["email"],
    ),
    # WordApp (office/word.py)
    _tool(
        "word_close_document",
        "Word (Open, edit, save, and print .docx files via Microsoft Word.): close document.",
        {},
        [],
    ),
    _tool(
        "word_new_document", "Word (Open, edit, save, and print .docx files via Microsoft Word.): new document.", {}, []
    ),
    _tool(
        "word_open_file",
        "Word (Open, edit, save, and print .docx files via Microsoft Word.): open file.",
        {"path": {"type": "string"}},
        ["path"],
    ),
    _tool(
        "word_print_document",
        "Word (Open, edit, save, and print .docx files via Microsoft Word.): print document.",
        {},
        [],
    ),
    _tool("word_save", "Word (Open, edit, save, and print .docx files via Microsoft Word.): save.", {}, []),
    _tool(
        "word_save_as",
        "Word: Opens the Save As dialog and types the path - the dialog still",
        {"path": {"type": "string"}},
        ["path"],
    ),
    # DiscordApp (communication/discord.py)
    _tool(
        "discord_open_channel",
        "Discord (Open servers/channels and send messages via Discord Desktop.): open channel.",
        {"server_id": {"type": "string"}, "channel_id": {"type": "string"}},
        ["server_id", "channel_id"],
    ),
    _tool(
        "discord_open_dm",
        "Discord (Open servers/channels and send messages via Discord Desktop.): open dm.",
        {"channel_id": {"type": "string"}},
        ["channel_id"],
    ),
    _tool(
        "discord_send_message_to_open_channel",
        "Discord: Sends into whichever channel is currently focused in Discord -",
        {"message": {"type": "string"}},
        ["message"],
    ),
    # MessengerApp (communication/messenger.py)
    _tool(
        "messenger_open_chat",
        "Messenger (Open chats via m.me and send messages in Messenger (web/desktop).): open chat.",
        {"username": {"type": "string"}},
        ["username"],
    ),
    _tool(
        "messenger_send_message",
        "Messenger (Open chats via m.me and send messages in Messenger (web/desktop).): send message.",
        {"username": {"type": "string"}, "message": {"type": "string"}, "wait_seconds": {"type": "number"}},
        ["username", "message"],
    ),
    # SignalApp (communication/signal.py)
    _tool(
        "signal_send_message_to_open_chat",
        "Signal: Sends into whichever chat is currently open/focused in Signal -",
        {"message": {"type": "string"}},
        ["message"],
    ),
    # SkypeApp (communication/skype.py)
    _tool(
        "skype_call",
        "Skype (Open chats and place calls via Skype's skype: protocol handler.): call.",
        {"contact": {"type": "string"}, "video": {"type": "boolean"}},
        ["contact"],
    ),
    _tool(
        "skype_open_chat",
        "Skype (Open chats and place calls via Skype's skype: protocol handler.): open chat.",
        {"contact": {"type": "string"}},
        ["contact"],
    ),
    _tool(
        "skype_send_message_to_open_chat",
        "Skype (Open chats and place calls via Skype's skype: protocol handler.): send message to open chat.",
        {"message": {"type": "string"}},
        ["message"],
    ),
    # SlackApp (communication/slack.py)
    _tool(
        "slack_jump_to",
        "Slack: Ctrl+K quick-switcher, typed query, Enter to jump to a channel/DM by name.",
        {"query": {"type": "string"}},
        ["query"],
    ),
    _tool(
        "slack_open_channel",
        "Slack (Open channels and send messages via Slack Desktop.): open channel.",
        {"team_id": {"type": "string"}, "channel_id": {"type": "string"}},
        ["team_id", "channel_id"],
    ),
    _tool(
        "slack_send_message_to_open_channel",
        "Slack: Sends into whichever channel is currently focused in Slack -",
        {"message": {"type": "string"}},
        ["message"],
    ),
    # TelegramApp (communication/telegram.py)
    _tool(
        "telegram_open_chat",
        "Telegram (Open chats and send messages via Telegram Desktop.): open chat.",
        {"username": {"type": "string"}},
        ["username"],
    ),
    _tool(
        "telegram_send_message",
        "Telegram (Open chats and send messages via Telegram Desktop.): send message.",
        {"username": {"type": "string"}, "message": {"type": "string"}, "wait_seconds": {"type": "number"}},
        ["username", "message"],
    ),
    # WhatsAppApp (communication/whatsapp.py)
    _tool(
        "whatsapp_open_chat",
        "WhatsApp (Open chats and send messages via WhatsApp Desktop/Web.): open chat. Requires a PHONE NUMBER - if you only have a contact's name, use whatsapp_send_message_by_name instead.",
        {"phone": {"type": "string"}, "message": {"type": "string"}},
        ["phone"],
    ),
    _tool(
        "whatsapp_send_message",
        "WhatsApp: Opens the chat pre-filled with the message, waits for it to load, then sends. Requires a real PHONE NUMBER you already have - never invent/guess one. If you only have the contact's NAME, use whatsapp_send_message_by_name instead.",
        {"phone": {"type": "string"}, "message": {"type": "string"}, "wait_seconds": {"type": "number"}},
        ["phone", "message"],
    ),
    _tool(
        "whatsapp_send_message_by_name",
        "WhatsApp: THE tool to use whenever the user names a person instead of giving a phone number (e.g. 'send Mummy a WhatsApp message', 'message Mummy on WhatsApp') - do NOT use send_whatsapp_message or whatsapp_send_message for this, both require a phone number you don't have. This searches WhatsApp Desktop's own New chat contact list by name (case-insensitive) and sends directly on a single unambiguous match. If 2+ saved contacts share that exact name, it returns needs_confirmation with the list of matches instead of guessing - you MUST then ask the user which one they mean (e.g. 'Which Mummy - the one saved as +91... or +91...?') and call this again with match_index set to their choice. If it returns a plain error (0 matches), tell the user no WhatsApp contact was found under that name and ask them to confirm the exact saved name or give the number - never claim 'no contact found' without having actually called this tool first.",
        {
            "name": {"type": "string"},
            "message": {"type": "string"},
            "match_index": {
                "type": "integer",
                "description": "0-based index into a previous needs_confirmation matches list - only set this on the confirmed follow-up call.",
            },
        },
        ["name", "message"],
    ),
    _tool(
        "whatsapp_find_chat_matches",
        "WhatsApp: search WhatsApp Desktop's New chat contact list for a NAME and list what it finds, without sending anything. Useful to check who's actually saved under a name before messaging them.",
        {"name": {"type": "string"}},
        ["name"],
    ),
    # ITunesApp (media/itunes.py)
    _tool("itunes_next_track", "ITunes (Open iTunes and control playback via system media keys.): next track.", {}, []),
    _tool(
        "itunes_play_file",
        "ITunes (Open iTunes and control playback via system media keys.): play file.",
        {"path": {"type": "string"}},
        ["path"],
    ),
    _tool("itunes_play_pause", "ITunes (Open iTunes and control playback via system media keys.): play pause.", {}, []),
    _tool(
        "itunes_previous_track",
        "ITunes (Open iTunes and control playback via system media keys.): previous track.",
        {},
        [],
    ),
    # SpotifyApp (media/spotify.py)
    _tool(
        "spotify_next_track",
        "Spotify (Search/play via the Spotify Web API, or fall back to media keys.): next track.",
        {},
        [],
    ),
    _tool(
        "spotify_play_pause",
        "Spotify (Search/play via the Spotify Web API, or fall back to media keys.): play pause.",
        {},
        [],
    ),
    _tool(
        "spotify_previous_track",
        "Spotify (Search/play via the Spotify Web API, or fall back to media keys.): previous track.",
        {},
        [],
    ),
    _tool(
        "spotify_search_and_play",
        "Spotify (Search/play via the Spotify Web API, or fall back to media keys.): search and play.",
        {"query": {"type": "string"}},
        ["query"],
    ),
    # VLCApp (media/vlc.py)
    _tool("vlc_fullscreen", "VLC (Open media files and control playback in VLC.): fullscreen.", {}, []),
    _tool("vlc_next_track", "VLC (Open media files and control playback in VLC.): next track.", {}, []),
    _tool(
        "vlc_play_file",
        "VLC (Open media files and control playback in VLC.): play file.",
        {"path": {"type": "string"}},
        ["path"],
    ),
    _tool("vlc_play_pause", "VLC (Open media files and control playback in VLC.): play pause.", {}, []),
    _tool("vlc_previous_track", "VLC (Open media files and control playback in VLC.): previous track.", {}, []),
    _tool("vlc_volume_down", "VLC (Open media files and control playback in VLC.): volume down.", {}, []),
    _tool("vlc_volume_up", "VLC (Open media files and control playback in VLC.): volume up.", {}, []),
    # WindowsMediaApp (media/windows_media.py)
    _tool(
        "windows_media_mute",
        "WindowsMedia (Open Windows Media Player and control system-wide media playback.): mute.",
        {},
        [],
    ),
    _tool(
        "windows_media_next_track",
        "WindowsMedia (Open Windows Media Player and control system-wide media playback.): next track.",
        {},
        [],
    ),
    _tool(
        "windows_media_play_file",
        "WindowsMedia (Open Windows Media Player and control system-wide media playback.): play file.",
        {"path": {"type": "string"}},
        ["path"],
    ),
    _tool(
        "windows_media_play_pause",
        "WindowsMedia (Open Windows Media Player and control system-wide media playback.): play pause.",
        {},
        [],
    ),
    _tool(
        "windows_media_previous_track",
        "WindowsMedia (Open Windows Media Player and control system-wide media playback.): previous track.",
        {},
        [],
    ),
    _tool(
        "windows_media_stop",
        "WindowsMedia (Open Windows Media Player and control system-wide media playback.): stop.",
        {},
        [],
    ),
    _tool(
        "windows_media_volume_down",
        "WindowsMedia (Open Windows Media Player and control system-wide media playback.): volume down.",
        {},
        [],
    ),
    _tool(
        "windows_media_volume_up",
        "WindowsMedia (Open Windows Media Player and control system-wide media playback.): volume up.",
        {},
        [],
    ),
    # YouTubeMusicApp (media/youtube_music.py)
    _tool(
        "youtube_music_next_track",
        "YouTubeMusic (Open music.youtube.com and control playback via media keys.): next track.",
        {},
        [],
    ),
    _tool(
        "youtube_music_open_web",
        "YouTubeMusic (Open music.youtube.com and control playback via media keys.): open web.",
        {},
        [],
    ),
    _tool(
        "youtube_music_play_pause",
        "YouTubeMusic (Open music.youtube.com and control playback via media keys.): play pause.",
        {},
        [],
    ),
    _tool(
        "youtube_music_previous_track",
        "YouTubeMusic (Open music.youtube.com and control playback via media keys.): previous track.",
        {},
        [],
    ),
    _tool(
        "youtube_music_search_and_open",
        "YouTubeMusic (Open music.youtube.com and control playback via media keys.): search and open.",
        {"query": {"type": "string"}},
        ["query"],
    ),
    # CanvaApp (design/canva.py)
    _tool(
        "canva_new_design",
        "Canva: design_type examples: 'presentation', 'instagram-post', 'poster'.",
        {"design_type": {"type": "string"}},
        [],
    ),
    _tool(
        "canva_open_design",
        "Canva (Open Canva and jump to a specific design.): open design.",
        {"design_url": {"type": "string"}},
        ["design_url"],
    ),
    _tool("canva_open_web", "Canva (Open Canva and jump to a specific design.): open web.", {}, []),
    # FigmaApp (design/figma.py)
    _tool(
        "figma_open_file",
        "Figma (Open Figma and jump to a specific file.): open file.",
        {"file_url": {"type": "string"}},
        ["file_url"],
    ),
    _tool("figma_open_web", "Figma (Open Figma and jump to a specific file.): open web.", {}, []),
    # GimpApp (design/gimp.py)
    _tool(
        "gimp_export_as",
        "Gimp: Opens the Export As dialog (Shift+Ctrl+E); pass a path via a",
        {"script_fu_export_path": {"type": "string"}},
        [],
    ),
    _tool(
        "gimp_open_file",
        "Gimp (Open image files and drive save/export in GIMP.): open file.",
        {"path": {"type": "string"}},
        ["path"],
    ),
    _tool(
        "gimp_run_batch_script",
        "Gimp: Runs GIMP in headless batch mode with a Script-Fu command -",
        {"script_fu_command": {"type": "string"}},
        ["script_fu_command"],
    ),
    _tool("gimp_save_xcf", "Gimp (Open image files and drive save/export in GIMP.): save xcf.", {}, []),
    # IllustratorApp (design/illustrator.py)
    _tool(
        "illustrator_export", "Illustrator (Open vector files and drive save/export in Illustrator.): export.", {}, []
    ),
    _tool(
        "illustrator_open_file",
        "Illustrator (Open vector files and drive save/export in Illustrator.): open file.",
        {"path": {"type": "string"}},
        ["path"],
    ),
    _tool("illustrator_save", "Illustrator (Open vector files and drive save/export in Illustrator.): save.", {}, []),
    # PhotoshopApp (design/photoshop.py)
    _tool(
        "photoshop_export_for_web",
        "Photoshop (Open image files and drive save/export in Photoshop.): export for web.",
        {},
        [],
    ),
    _tool(
        "photoshop_open_file",
        "Photoshop (Open image files and drive save/export in Photoshop.): open file.",
        {"path": {"type": "string"}},
        ["path"],
    ),
    _tool("photoshop_save", "Photoshop (Open image files and drive save/export in Photoshop.): save.", {}, []),
    _tool("photoshop_undo", "Photoshop (Open image files and drive save/export in Photoshop.): undo.", {}, []),
    # DockerApp (development/docker.py)
    _tool(
        "docker_list_containers",
        "Docker (List/start/stop containers and images via the Docker CLI.): list containers.",
        {"all_containers": {"type": "boolean"}},
        [],
    ),
    _tool(
        "docker_list_images", "Docker (List/start/stop containers and images via the Docker CLI.): list images.", {}, []
    ),
    _tool(
        "docker_logs",
        "Docker (List/start/stop containers and images via the Docker CLI.): logs.",
        {"name_or_id": {"type": "string"}, "tail": {"type": "integer"}},
        ["name_or_id"],
    ),
    _tool(
        "docker_remove_container",
        "Docker (List/start/stop containers and images via the Docker CLI.): remove container.",
        {"name_or_id": {"type": "string"}, "force": {"type": "boolean"}},
        ["name_or_id"],
    ),
    _tool(
        "docker_run_container",
        "Docker (List/start/stop containers and images via the Docker CLI.): run container.",
        {"image": {"type": "string"}, "args": {"type": "array"}, "detached": {"type": "boolean"}},
        ["image"],
    ),
    _tool(
        "docker_start_container",
        "Docker (List/start/stop containers and images via the Docker CLI.): start container.",
        {"name_or_id": {"type": "string"}},
        ["name_or_id"],
    ),
    _tool(
        "docker_stop_container",
        "Docker (List/start/stop containers and images via the Docker CLI.): stop container.",
        {"name_or_id": {"type": "string"}},
        ["name_or_id"],
    ),
    # GitApp (development/git.py)
    _tool(
        "git_add_all",
        "Git (Clone, commit, push, and pull via the Git CLI.): add all.",
        {"repo_path": {"type": "string"}},
        ["repo_path"],
    ),
    _tool(
        "git_clone",
        "Git (Clone, commit, push, and pull via the Git CLI.): clone.",
        {"url": {"type": "string"}, "destination": {"type": "string"}},
        ["url"],
    ),
    _tool(
        "git_commit",
        "Git (Clone, commit, push, and pull via the Git CLI.): commit.",
        {"repo_path": {"type": "string"}, "message": {"type": "string"}},
        ["repo_path", "message"],
    ),
    _tool(
        "git_create_branch",
        "Git (Clone, commit, push, and pull via the Git CLI.): create branch.",
        {"repo_path": {"type": "string"}, "branch_name": {"type": "string"}},
        ["repo_path", "branch_name"],
    ),
    _tool(
        "git_current_branch",
        "Git (Clone, commit, push, and pull via the Git CLI.): current branch.",
        {"repo_path": {"type": "string"}},
        ["repo_path"],
    ),
    _tool(
        "git_log",
        "Git (Clone, commit, push, and pull via the Git CLI.): log.",
        {"repo_path": {"type": "string"}, "count": {"type": "integer"}},
        ["repo_path"],
    ),
    _tool(
        "git_pull",
        "Git (Clone, commit, push, and pull via the Git CLI.): pull.",
        {"repo_path": {"type": "string"}},
        ["repo_path"],
    ),
    _tool(
        "git_push",
        "Git (Clone, commit, push, and pull via the Git CLI.): push.",
        {"repo_path": {"type": "string"}, "remote": {"type": "string"}, "branch": {"type": "string"}},
        ["repo_path"],
    ),
    _tool(
        "git_status",
        "Git (Clone, commit, push, and pull via the Git CLI.): status.",
        {"repo_path": {"type": "string"}},
        ["repo_path"],
    ),
    # PostmanApp (development/postman.py)
    _tool(
        "postman_open_collection_link",
        "Postman (Open Postman, or a shared collection link, for API testing.): open collection link.",
        {"collection_url": {"type": "string"}},
        ["collection_url"],
    ),
    # PyCharmApp (development/pycharm.py)
    _tool(
        "pycharm_open_project",
        "PyCharm (Open projects/files in PyCharm.): open project.",
        {"path": {"type": "string"}},
        ["path"],
    ),
    # TerminalApp (development/terminal.py)
    _tool(
        "terminal_open_here",
        "Terminal: Open a visible terminal window with its working directory set to path.",
        {"path": {"type": "string"}},
        ["path"],
    ),
    _tool(
        "terminal_run_and_capture_command",
        "Terminal: Run a shell command and wait for its output.",
        {"command": {"type": "string"}, "timeout": {"type": "number"}},
        ["command"],
    ),
    _tool(
        "terminal_run_command",
        "Terminal: Accepts either a list of args or a single shell command string.",
        {"args": {"type": "string"}},
        ["args"],
    ),
    # VSCodeApp (development/vscode.py)
    _tool(
        "vscode_diff",
        "VSCode (Open folders/files and manage extensions via the `code` CLI.): diff.",
        {"file1": {"type": "string"}, "file2": {"type": "string"}},
        ["file1", "file2"],
    ),
    _tool(
        "vscode_install_extension",
        "VSCode (Open folders/files and manage extensions via the `code` CLI.): install extension.",
        {"extension_id": {"type": "string"}},
        ["extension_id"],
    ),
    _tool(
        "vscode_list_extensions",
        "VSCode (Open folders/files and manage extensions via the `code` CLI.): list extensions.",
        {},
        [],
    ),
    _tool(
        "vscode_new_window",
        "VSCode (Open folders/files and manage extensions via the `code` CLI.): new window.",
        {},
        [],
    ),
    _tool(
        "vscode_open_file",
        "VSCode (Open folders/files and manage extensions via the `code` CLI.): open file.",
        {"path": {"type": "string"}, "line": {"type": "integer"}},
        ["path"],
    ),
    _tool(
        "vscode_open_folder",
        "VSCode (Open folders/files and manage extensions via the `code` CLI.): open folder.",
        {"path": {"type": "string"}},
        ["path"],
    ),
    # GoogleDriveApp (cloud/google_drive.py)
    _tool(
        "google_drive_new_folder_web",
        "GoogleDrive: Google Drive has no simple URL scheme for creating a named",
        {"name": {"type": "string"}},
        ["name"],
    ),
    # ControlPanelApp (system/control_panel.py)
    _tool(
        "control_panel_list_applets",
        "ControlPanel (Open Control Panel or jump straight to a named applet.): list applets.",
        {},
        [],
    ),
    _tool(
        "control_panel_open_applet",
        "ControlPanel (Open Control Panel or jump straight to a named applet.): open applet.",
        {"applet_name": {"type": "string"}},
        ["applet_name"],
    ),
    # DeviceManagerApp (system/device_manager.py)
    _tool(
        "device_manager_list_devices",
        "DeviceManager (Open Device Manager and list connected devices.): list devices.",
        {"only_problems": {"type": "boolean"}},
        [],
    ),
    _tool(
        "device_manager_open", "DeviceManager: Launch the app via its Start Menu shortcut / App Paths entry.", {}, []
    ),
    # FileExplorerApp (system/file_explorer.py)
    _tool(
        "file_explorer_open_downloads",
        "FileExplorer (Open folders, select files, and jump to common shell locations.): open downloads.",
        {},
        [],
    ),
    _tool(
        "file_explorer_open_path",
        "FileExplorer (Open folders, select files, and jump to common shell locations.): open path.",
        {"path": {"type": "string"}},
        ["path"],
    ),
    _tool(
        "file_explorer_open_recycle_bin",
        "FileExplorer (Open folders, select files, and jump to common shell locations.): open recycle bin.",
        {},
        [],
    ),
    _tool(
        "file_explorer_open_this_pc",
        "FileExplorer (Open folders, select files, and jump to common shell locations.): open this pc.",
        {},
        [],
    ),
    _tool(
        "file_explorer_select_file",
        "FileExplorer: Opens Explorer with the file highlighted (rather than opening it).",
        {"path": {"type": "string"}},
        ["path"],
    ),
    # PowerShellApp (system/powershell.py)
    _tool(
        "powershell_open_console",
        "PowerShell (Run PowerShell commands/scripts and capture their output.): open console.",
        {},
        [],
    ),
    _tool(
        "powershell_run_command",
        "PowerShell: Launch a process directly (real exe + arbitrary CLI args).",
        {"command": {"type": "string"}, "timeout": {"type": "number"}},
        ["command"],
    ),
    _tool(
        "powershell_run_script",
        "PowerShell (Run PowerShell commands/scripts and capture their output.): run script.",
        {"script_path": {"type": "string"}, "timeout": {"type": "number"}},
        ["script_path"],
    ),
    # RegistryApp (system/registry.py)
    _tool(
        "registry_list_values",
        "Registry (Open regedit and read/write/list registry keys and values.): list values.",
        {"root": {"type": "string"}, "key_path": {"type": "string"}},
        ["root", "key_path"],
    ),
    _tool(
        "registry_read_value",
        "Registry (Open regedit and read/write/list registry keys and values.): read value.",
        {"root": {"type": "string"}, "key_path": {"type": "string"}, "value_name": {"type": "string"}},
        ["root", "key_path", "value_name"],
    ),
    _tool(
        "registry_set_value",
        "Registry (Open regedit and read/write/list registry keys and values.): set value.",
        {
            "root": {"type": "string"},
            "key_path": {"type": "string"},
            "value_name": {"type": "string"},
            "value": {"type": "string"},
            "value_type": {"type": "string"},
        },
        ["root", "key_path", "value_name", "value"],
    ),
    # SettingsApp (system/settings.py)
    _tool(
        "settings_list_pages",
        "Settings (Open the Windows Settings app, optionally to a specific page.): list pages.",
        {},
        [],
    ),
    _tool(
        "settings_open_page",
        "Settings (Open the Windows Settings app, optionally to a specific page.): open page.",
        {"page": {"type": "string"}},
        ["page"],
    ),
    # TaskManagerApp (system/task_manager.py)
    _tool(
        "task_manager_end_task",
        "TaskManager (Open Task Manager, list processes, and end tasks.): end task.",
        {"name_or_pid": {"type": "string"}},
        ["name_or_pid"],
    ),
    _tool(
        "task_manager_list_processes",
        "TaskManager (Open Task Manager, list processes, and end tasks.): list processes.",
        {"sort_by_memory": {"type": "boolean"}},
        [],
    ),
    # CalculatorApp (utilities/calculator.py)
    _tool(
        "calculator_compute",
        "Calculator (Open the Calculator app and evaluate arithmetic expressions.): compute.",
        {"expression": {"type": "string"}},
        ["expression"],
    ),
    # NotepadApp (utilities/notepad.py)
    _tool(
        "notepad_append_text",
        "Notepad (Open, write, and append plain-text files via Notepad.): append text.",
        {"path": {"type": "string"}, "text": {"type": "string"}},
        ["path", "text"],
    ),
    _tool(
        "notepad_new_note",
        "Notepad (Open, write, and append plain-text files via Notepad.): new note.",
        {"text": {"type": "string"}},
        [],
    ),
    _tool(
        "notepad_open_file",
        "Notepad (Open, write, and append plain-text files via Notepad.): open file.",
        {"path": {"type": "string"}},
        ["path"],
    ),
    _tool(
        "notepad_write_text",
        "Notepad (Open, write, and append plain-text files via Notepad.): write text.",
        {"path": {"type": "string"}, "text": {"type": "string"}},
        ["path", "text"],
    ),
    # PaintApp (utilities/paint.py)
    _tool("paint_new_canvas", "Paint (Open image files and a blank canvas via Paint.): new canvas.", {}, []),
    _tool(
        "paint_open_file",
        "Paint (Open image files and a blank canvas via Paint.): open file.",
        {"path": {"type": "string"}},
        ["path"],
    ),
    # PDFReaderApp (utilities/pdf_reader.py)
    _tool(
        "pdf_reader_open_file",
        "PDFReader (Open PDF files, optionally jumped to a specific page.): open file.",
        {"path": {"type": "string"}, "page": {"type": "integer"}},
        ["path"],
    ),
    # SnippingToolApp (utilities/snipping_tool.py)
    _tool(
        "snipping_tool_capture_region",
        "SnippingTool (Open the Snipping Tool, or capture the screen/a region directly.): capture region.",
        {
            "x": {"type": "integer"},
            "y": {"type": "integer"},
            "width": {"type": "integer"},
            "height": {"type": "integer"},
            "save_path": {"type": "string"},
        },
        ["x", "y", "width", "height"],
    ),
    _tool(
        "snipping_tool_capture_screen",
        "SnippingTool (Open the Snipping Tool, or capture the screen/a region directly.): capture screen.",
        {"save_path": {"type": "string"}},
        [],
    ),
    _tool(
        "snipping_tool_open_interactive",
        "SnippingTool: Windows key + Shift + S starts an interactive region snip.",
        {},
        [],
    ),
    # StickyNotesApp (utilities/sticky_notes.py)
    _tool(
        "sticky_notes_new_note",
        "StickyNotes (Open Sticky Notes and create a new note with text.): new note.",
        {"text": {"type": "string"}},
        ["text"],
    ),
    # WinRARApp (utilities/winrar.py)
    _tool(
        "winrar_compress",
        "WinRAR (Compress and extract archives via WinRAR (or zipfile fallback).): compress.",
        {"files": {"type": "array"}, "archive_path": {"type": "string"}},
        ["files", "archive_path"],
    ),
    _tool(
        "winrar_extract",
        "WinRAR (Compress and extract archives via WinRAR (or zipfile fallback).): extract.",
        {"archive_path": {"type": "string"}, "destination": {"type": "string"}},
        ["archive_path", "destination"],
    ),
    _tool(
        "winrar_list_contents",
        "WinRAR (Compress and extract archives via WinRAR (or zipfile fallback).): list contents.",
        {"archive_path": {"type": "string"}},
        ["archive_path"],
    ),
    # AntivirusApp (security/antivirus.py)
    _tool(
        "antivirus_get_status",
        "Antivirus (Query which antivirus product(s) Windows Security Center sees.): get status.",
        {},
        [],
    ),
    # BitLockerApp (security/bitlocker.py)
    _tool(
        "bitlocker_get_all_status", "BitLocker (Check BitLocker encryption status per drive.): get all status.", {}, []
    ),
    _tool(
        "bitlocker_get_status",
        "BitLocker (Check BitLocker encryption status per drive.): get status.",
        {"drive": {"type": "string"}},
        [],
    ),
    # FirewallApp (security/firewall.py)
    _tool(
        "firewall_disable",
        "Firewall (Check status and toggle Windows Firewall profiles.): disable.",
        {"profile": {"type": "string"}},
        [],
    ),
    _tool(
        "firewall_enable",
        "Firewall (Check status and toggle Windows Firewall profiles.): enable.",
        {"profile": {"type": "string"}},
        [],
    ),
    _tool("firewall_get_status", "Firewall (Check status and toggle Windows Firewall profiles.): get status.", {}, []),
    _tool("firewall_list_rules", "Firewall (Check status and toggle Windows Firewall profiles.): list rules.", {}, []),
    _tool(
        "firewall_open_console", "Firewall (Check status and toggle Windows Firewall profiles.): open console.", {}, []
    ),
    # WindowsDefenderApp (security/windows_defender.py)
    _tool(
        "windows_defender_get_status",
        "WindowsDefender (Check status and run scans via Windows Defender.): get status.",
        {},
        [],
    ),
    _tool(
        "windows_defender_open_security_center",
        "WindowsDefender (Check status and run scans via Windows Defender.): open security center.",
        {},
        [],
    ),
    _tool(
        "windows_defender_run_quick_scan",
        "WindowsDefender (Check status and run scans via Windows Defender.): run quick scan.",
        {},
        [],
    ),
    _tool(
        "windows_defender_update_definitions",
        "WindowsDefender (Check status and run scans via Windows Defender.): update definitions.",
        {},
        [],
    ),
    # DiscordGamingApp (gaming/discord_gaming.py)
    _tool(
        "discord_gaming_detect_running_games",
        "DiscordGaming (Detect running games and jump into voice/gaming channels on Discord.): detect running games.",
        {},
        [],
    ),
    _tool(
        "discord_gaming_join_voice_channel",
        "DiscordGaming (Detect running games and jump into voice/gaming channels on Discord.): join voice channel.",
        {"server_id": {"type": "string"}, "channel_id": {"type": "string"}},
        ["server_id", "channel_id"],
    ),
    _tool(
        "discord_gaming_open_and_detect",
        "DiscordGaming (Detect running games and jump into voice/gaming channels on Discord.): open and detect.",
        {},
        [],
    ),
    # EpicGamesApp (gaming/epic_games.py)
    _tool(
        "epic_games_launch_game",
        "EpicGames (Open the Epic Games Launcher and launch games by their app name.): launch game.",
        {"app_name": {"type": "string"}, "silent": {"type": "boolean"}},
        ["app_name"],
    ),
    _tool(
        "epic_games_open_store",
        "EpicGames (Open the Epic Games Launcher and launch games by their app name.): open store.",
        {},
        [],
    ),
    # SteamApp (gaming/steam.py)
    _tool(
        "steam_launch_game",
        "Steam (Open Steam, launch games by App ID, and jump to the store/library.): launch game.",
        {"app_id": {"type": "string"}},
        ["app_id"],
    ),
    _tool(
        "steam_open_friends",
        "Steam (Open Steam, launch games by App ID, and jump to the store/library.): open friends.",
        {},
        [],
    ),
    _tool(
        "steam_open_library",
        "Steam (Open Steam, launch games by App ID, and jump to the store/library.): open library.",
        {},
        [],
    ),
    _tool(
        "steam_open_store_page",
        "Steam (Open Steam, launch games by App ID, and jump to the store/library.): open store page.",
        {"app_id": {"type": "string"}},
        ["app_id"],
    ),
    # XboxApp (gaming/xbox.py)
    _tool("xbox_open_app", "Xbox (Open the Xbox app and jump to the game bar / social panel.): open app.", {}, []),
    _tool("xbox_open_game_bar", "Xbox: Windows key + G opens the Xbox Game Bar overlay.", {}, []),
    _tool("xbox_screenshot", "Xbox: Windows key + Alt + PrtScn takes a Game Bar screenshot.", {}, []),
    _tool("xbox_take_game_clip", "Xbox: Windows key + Alt + G records the last N seconds via Game Bar.", {}, []),
]


APPS_DIRECT_HANDLERS = {
    "app_open": lambda d: _get(d.get("app", "")).open(),
    "app_close": lambda d: _get(d.get("app", "")).close(),
    "app_focus": lambda d: _get(d.get("app", "")).focus(),
    "app_is_running": lambda d: _get(d.get("app", "")).is_running(),
    "list_available_apps": lambda d: {"success": True, "apps": sorted(APP_REGISTRY)},
    # -- BraveApp --
    "brave_close_all": lambda d, _k="brave", _m="close_all", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "brave_new_tab": lambda d, _k="brave", _m="new_tab", _p=["url"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "brave_new_window": lambda d, _k="brave", _m="new_window", _p=["url"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "brave_open_private_window": lambda d, _k="brave", _m="open_private_window", _p=["url"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "brave_open_tor_window": lambda d, _k="brave", _m="open_tor_window", _p=["url"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "brave_open_url": lambda d, _k="brave", _m="open_url", _p=["url", "private", "tor", "new_window"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "brave_search": lambda d, _k="brave", _m="search", _p=["query"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- ChromeApp --
    "chrome_bookmark_current_page": lambda d, _k="chrome", _m="bookmark_current_page", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "chrome_close_all": lambda d, _k="chrome", _m="close_all", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "chrome_close_tab": lambda d, _k="chrome", _m="close_tab", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "chrome_new_tab": lambda d, _k="chrome", _m="new_tab", _p=["url"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "chrome_new_window": lambda d, _k="chrome", _m="new_window", _p=["url"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "chrome_open_incognito": lambda d, _k="chrome", _m="open_incognito", _p=["url"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "chrome_open_url": lambda d, _k="chrome", _m="open_url", _p=["url", "incognito", "new_window"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "chrome_search": lambda d, _k="chrome", _m="search", _p=["query"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- EdgeApp --
    "edge_close_all": lambda d, _k="edge", _m="close_all", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "edge_close_tab": lambda d, _k="edge", _m="close_tab", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "edge_new_tab": lambda d, _k="edge", _m="new_tab", _p=["url"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "edge_new_window": lambda d, _k="edge", _m="new_window", _p=["url"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "edge_open_inprivate": lambda d, _k="edge", _m="open_inprivate", _p=["url"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "edge_open_url": lambda d, _k="edge", _m="open_url", _p=["url", "private", "new_window"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "edge_search": lambda d, _k="edge", _m="search", _p=["query"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- FirefoxApp --
    "firefox_close_all": lambda d, _k="firefox", _m="close_all", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "firefox_close_tab": lambda d, _k="firefox", _m="close_tab", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "firefox_new_tab": lambda d, _k="firefox", _m="new_tab", _p=["url"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "firefox_new_window": lambda d, _k="firefox", _m="new_window", _p=["url"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "firefox_open_private_window": lambda d, _k="firefox", _m="open_private_window", _p=["url"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "firefox_open_url": lambda d, _k="firefox", _m="open_url", _p=["url", "private", "new_window"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "firefox_search": lambda d, _k="firefox", _m="search", _p=["query"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- OperaApp --
    "opera_close_all": lambda d, _k="opera", _m="close_all", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "opera_new_tab": lambda d, _k="opera", _m="new_tab", _p=["url"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "opera_new_window": lambda d, _k="opera", _m="new_window", _p=["url"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "opera_open_private_window": lambda d, _k="opera", _m="open_private_window", _p=["url"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "opera_open_url": lambda d, _k="opera", _m="open_url", _p=["url", "private", "new_window"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "opera_search": lambda d, _k="opera", _m="search", _p=["query"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- AccessApp --
    "access_new_database": lambda d, _k="access", _m="new_database", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "access_open_database": lambda d, _k="access", _m="open_database", _p=["path"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- ExcelApp --
    "excel_close_workbook": lambda d, _k="excel", _m="close_workbook", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "excel_new_sheet": lambda d, _k="excel", _m="new_sheet", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "excel_new_workbook": lambda d, _k="excel", _m="new_workbook", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "excel_open_file": lambda d, _k="excel", _m="open_file", _p=["path"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "excel_print_workbook": lambda d, _k="excel", _m="print_workbook", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "excel_save": lambda d, _k="excel", _m="save", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- OneNoteApp --
    "onenote_new_page": lambda d, _k="onenote", _m="new_page", _p=["title"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "onenote_quick_note": lambda d, _k="onenote", _m="quick_note", _p=["text"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- OutlookApp --
    "outlook_compose_email": lambda d, _k="outlook", _m="compose_email", _p=["to", "subject", "body", "cc"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "outlook_new_meeting": lambda d, _k="outlook", _m="new_meeting", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "outlook_open_calendar": lambda d, _k="outlook", _m="open_calendar", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "outlook_open_inbox": lambda d, _k="outlook", _m="open_inbox", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- PowerPointApp --
    "powerpoint_end_slideshow": lambda d, _k="powerpoint", _m="end_slideshow", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "powerpoint_new_presentation": lambda d, _k="powerpoint", _m="new_presentation", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "powerpoint_next_slide": lambda d, _k="powerpoint", _m="next_slide", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "powerpoint_open_file": lambda d, _k="powerpoint", _m="open_file", _p=["path"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "powerpoint_previous_slide": lambda d, _k="powerpoint", _m="previous_slide", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "powerpoint_save": lambda d, _k="powerpoint", _m="save", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "powerpoint_start_slideshow": lambda d, _k="powerpoint", _m="start_slideshow", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- TeamsApp --
    "teams_join_meeting": lambda d, _k="teams", _m="join_meeting", _p=["meeting_url"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "teams_open_chat": lambda d, _k="teams", _m="open_chat", _p=["email"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "teams_start_call": lambda d, _k="teams", _m="start_call", _p=["email", "video"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- WordApp --
    "word_close_document": lambda d, _k="word", _m="close_document", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "word_new_document": lambda d, _k="word", _m="new_document", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "word_open_file": lambda d, _k="word", _m="open_file", _p=["path"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "word_print_document": lambda d, _k="word", _m="print_document", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "word_save": lambda d, _k="word", _m="save", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "word_save_as": lambda d, _k="word", _m="save_as", _p=["path"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- DiscordApp --
    "discord_open_channel": lambda d, _k="discord", _m="open_channel", _p=["server_id", "channel_id"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "discord_open_dm": lambda d, _k="discord", _m="open_dm", _p=["channel_id"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "discord_send_message_to_open_channel": lambda d, _k="discord", _m="send_message_to_open_channel", _p=[
        "message"
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- MessengerApp --
    "messenger_open_chat": lambda d, _k="messenger", _m="open_chat", _p=["username"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "messenger_send_message": lambda d, _k="messenger", _m="send_message", _p=[
        "username",
        "message",
        "wait_seconds",
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- SignalApp --
    "signal_send_message_to_open_chat": lambda d, _k="signal", _m="send_message_to_open_chat", _p=["message"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    # -- SkypeApp --
    "skype_call": lambda d, _k="skype", _m="call", _p=["contact", "video"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "skype_open_chat": lambda d, _k="skype", _m="open_chat", _p=["contact"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "skype_send_message_to_open_chat": lambda d, _k="skype", _m="send_message_to_open_chat", _p=["message"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    # -- SlackApp --
    "slack_jump_to": lambda d, _k="slack", _m="jump_to", _p=["query"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "slack_open_channel": lambda d, _k="slack", _m="open_channel", _p=["team_id", "channel_id"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "slack_send_message_to_open_channel": lambda d, _k="slack", _m="send_message_to_open_channel", _p=[
        "message"
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- TelegramApp --
    "telegram_open_chat": lambda d, _k="telegram", _m="open_chat", _p=["username"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "telegram_send_message": lambda d, _k="telegram", _m="send_message", _p=[
        "username",
        "message",
        "wait_seconds",
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- WhatsAppApp --
    "whatsapp_open_chat": lambda d, _k="whatsapp", _m="open_chat", _p=["phone", "message"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "whatsapp_send_message": lambda d, _k="whatsapp", _m="send_message", _p=[
        "phone",
        "message",
        "wait_seconds",
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "whatsapp_send_message_by_name": lambda d, _k="whatsapp", _m="send_message_by_name", _p=[
        "name",
        "message",
        "match_index",
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "whatsapp_find_chat_matches": lambda d, _k="whatsapp", _m="find_chat_matches", _p=["name"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- ITunesApp --
    "itunes_next_track": lambda d, _k="itunes", _m="next_track", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "itunes_play_file": lambda d, _k="itunes", _m="play_file", _p=["path"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "itunes_play_pause": lambda d, _k="itunes", _m="play_pause", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "itunes_previous_track": lambda d, _k="itunes", _m="previous_track", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- SpotifyApp --
    "spotify_next_track": lambda d, _k="spotify", _m="next_track", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "spotify_play_pause": lambda d, _k="spotify", _m="play_pause", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "spotify_previous_track": lambda d, _k="spotify", _m="previous_track", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "spotify_search_and_play": lambda d, _k="spotify", _m="search_and_play", _p=["query"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- VLCApp --
    "vlc_fullscreen": lambda d, _k="vlc", _m="fullscreen", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "vlc_next_track": lambda d, _k="vlc", _m="next_track", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "vlc_play_file": lambda d, _k="vlc", _m="play_file", _p=["path"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "vlc_play_pause": lambda d, _k="vlc", _m="play_pause", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "vlc_previous_track": lambda d, _k="vlc", _m="previous_track", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "vlc_volume_down": lambda d, _k="vlc", _m="volume_down", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "vlc_volume_up": lambda d, _k="vlc", _m="volume_up", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- WindowsMediaApp --
    "windows_media_mute": lambda d, _k="windows_media", _m="mute", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "windows_media_next_track": lambda d, _k="windows_media", _m="next_track", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "windows_media_play_file": lambda d, _k="windows_media", _m="play_file", _p=["path"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "windows_media_play_pause": lambda d, _k="windows_media", _m="play_pause", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "windows_media_previous_track": lambda d, _k="windows_media", _m="previous_track", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "windows_media_stop": lambda d, _k="windows_media", _m="stop", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "windows_media_volume_down": lambda d, _k="windows_media", _m="volume_down", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "windows_media_volume_up": lambda d, _k="windows_media", _m="volume_up", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- YouTubeMusicApp --
    "youtube_music_next_track": lambda d, _k="youtube_music", _m="next_track", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "youtube_music_open_web": lambda d, _k="youtube_music", _m="open_web", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "youtube_music_play_pause": lambda d, _k="youtube_music", _m="play_pause", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "youtube_music_previous_track": lambda d, _k="youtube_music", _m="previous_track", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "youtube_music_search_and_open": lambda d, _k="youtube_music", _m="search_and_open", _p=["query"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    # -- CanvaApp --
    "canva_new_design": lambda d, _k="canva", _m="new_design", _p=["design_type"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "canva_open_design": lambda d, _k="canva", _m="open_design", _p=["design_url"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "canva_open_web": lambda d, _k="canva", _m="open_web", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- FigmaApp --
    "figma_open_file": lambda d, _k="figma", _m="open_file", _p=["file_url"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "figma_open_web": lambda d, _k="figma", _m="open_web", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- GimpApp --
    "gimp_export_as": lambda d, _k="gimp", _m="export_as", _p=["script_fu_export_path"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "gimp_open_file": lambda d, _k="gimp", _m="open_file", _p=["path"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "gimp_run_batch_script": lambda d, _k="gimp", _m="run_batch_script", _p=["script_fu_command"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "gimp_save_xcf": lambda d, _k="gimp", _m="save_xcf", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- IllustratorApp --
    "illustrator_export": lambda d, _k="illustrator", _m="export", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "illustrator_open_file": lambda d, _k="illustrator", _m="open_file", _p=["path"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "illustrator_save": lambda d, _k="illustrator", _m="save", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- PhotoshopApp --
    "photoshop_export_for_web": lambda d, _k="photoshop", _m="export_for_web", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "photoshop_open_file": lambda d, _k="photoshop", _m="open_file", _p=["path"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "photoshop_save": lambda d, _k="photoshop", _m="save", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "photoshop_undo": lambda d, _k="photoshop", _m="undo", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- DockerApp --
    "docker_list_containers": lambda d, _k="docker", _m="list_containers", _p=["all_containers"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "docker_list_images": lambda d, _k="docker", _m="list_images", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "docker_logs": lambda d, _k="docker", _m="logs", _p=["name_or_id", "tail"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "docker_remove_container": lambda d, _k="docker", _m="remove_container", _p=["name_or_id", "force"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "docker_run_container": lambda d, _k="docker", _m="run_container", _p=["image", "args", "detached"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "docker_start_container": lambda d, _k="docker", _m="start_container", _p=["name_or_id"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "docker_stop_container": lambda d, _k="docker", _m="stop_container", _p=["name_or_id"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- GitApp --
    "git_add_all": lambda d, _k="git", _m="add_all", _p=["repo_path"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "git_clone": lambda d, _k="git", _m="clone", _p=["url", "destination"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "git_commit": lambda d, _k="git", _m="commit", _p=["repo_path", "message"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "git_create_branch": lambda d, _k="git", _m="create_branch", _p=["repo_path", "branch_name"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "git_current_branch": lambda d, _k="git", _m="current_branch", _p=["repo_path"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "git_log": lambda d, _k="git", _m="log", _p=["repo_path", "count"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "git_pull": lambda d, _k="git", _m="pull", _p=["repo_path"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "git_push": lambda d, _k="git", _m="push", _p=["repo_path", "remote", "branch"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "git_status": lambda d, _k="git", _m="status", _p=["repo_path"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- PostmanApp --
    "postman_open_collection_link": lambda d, _k="postman", _m="open_collection_link", _p=["collection_url"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    # -- PyCharmApp --
    "pycharm_open_project": lambda d, _k="pycharm", _m="open_project", _p=["path"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- TerminalApp --
    "terminal_open_here": lambda d, _k="terminal", _m="open_here", _p=["path"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "terminal_run_and_capture_command": lambda d, _k="terminal", _m="run_and_capture_command", _p=[
        "command",
        "timeout",
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "terminal_run_command": lambda d, _k="terminal", _m="run_command", _p=["args"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- VSCodeApp --
    "vscode_diff": lambda d, _k="vscode", _m="diff", _p=["file1", "file2"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "vscode_install_extension": lambda d, _k="vscode", _m="install_extension", _p=["extension_id"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "vscode_list_extensions": lambda d, _k="vscode", _m="list_extensions", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "vscode_new_window": lambda d, _k="vscode", _m="new_window", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "vscode_open_file": lambda d, _k="vscode", _m="open_file", _p=["path", "line"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "vscode_open_folder": lambda d, _k="vscode", _m="open_folder", _p=["path"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- GoogleDriveApp --
    "google_drive_new_folder_web": lambda d, _k="google_drive", _m="new_folder_web", _p=["name"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- ControlPanelApp --
    "control_panel_list_applets": lambda d, _k="control_panel", _m="list_applets", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "control_panel_open_applet": lambda d, _k="control_panel", _m="open_applet", _p=["applet_name"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    # -- DeviceManagerApp --
    "device_manager_list_devices": lambda d, _k="device_manager", _m="list_devices", _p=["only_problems"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "device_manager_open": lambda d, _k="device_manager", _m="open", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- FileExplorerApp --
    "file_explorer_open_downloads": lambda d, _k="file_explorer", _m="open_downloads", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "file_explorer_open_path": lambda d, _k="file_explorer", _m="open_path", _p=["path"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "file_explorer_open_recycle_bin": lambda d, _k="file_explorer", _m="open_recycle_bin", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "file_explorer_open_this_pc": lambda d, _k="file_explorer", _m="open_this_pc", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "file_explorer_select_file": lambda d, _k="file_explorer", _m="select_file", _p=["path"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- PowerShellApp --
    "powershell_open_console": lambda d, _k="powershell", _m="open_console", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "powershell_run_command": lambda d, _k="powershell", _m="run_command", _p=["command", "timeout"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "powershell_run_script": lambda d, _k="powershell", _m="run_script", _p=["script_path", "timeout"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    # -- RegistryApp --
    "registry_list_values": lambda d, _k="registry", _m="list_values", _p=["root", "key_path"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "registry_read_value": lambda d, _k="registry", _m="read_value", _p=["root", "key_path", "value_name"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "registry_set_value": lambda d, _k="registry", _m="set_value", _p=[
        "root",
        "key_path",
        "value_name",
        "value",
        "value_type",
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- SettingsApp --
    "settings_list_pages": lambda d, _k="settings", _m="list_pages", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "settings_open_page": lambda d, _k="settings", _m="open_page", _p=["page"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- TaskManagerApp --
    "task_manager_end_task": lambda d, _k="task_manager", _m="end_task", _p=["name_or_pid"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "task_manager_list_processes": lambda d, _k="task_manager", _m="list_processes", _p=["sort_by_memory"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    # -- CalculatorApp --
    "calculator_compute": lambda d, _k="calculator", _m="compute", _p=["expression"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- NotepadApp --
    "notepad_append_text": lambda d, _k="notepad", _m="append_text", _p=["path", "text"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "notepad_new_note": lambda d, _k="notepad", _m="new_note", _p=["text"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "notepad_open_file": lambda d, _k="notepad", _m="open_file", _p=["path"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "notepad_write_text": lambda d, _k="notepad", _m="write_text", _p=["path", "text"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- PaintApp --
    "paint_new_canvas": lambda d, _k="paint", _m="new_canvas", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "paint_open_file": lambda d, _k="paint", _m="open_file", _p=["path"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- PDFReaderApp --
    "pdf_reader_open_file": lambda d, _k="pdf_reader", _m="open_file", _p=["path", "page"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- SnippingToolApp --
    "snipping_tool_capture_region": lambda d, _k="snipping_tool", _m="capture_region", _p=[
        "x",
        "y",
        "width",
        "height",
        "save_path",
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "snipping_tool_capture_screen": lambda d, _k="snipping_tool", _m="capture_screen", _p=["save_path"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "snipping_tool_open_interactive": lambda d, _k="snipping_tool", _m="open_interactive", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- StickyNotesApp --
    "sticky_notes_new_note": lambda d, _k="sticky_notes", _m="new_note", _p=["text"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- WinRARApp --
    "winrar_compress": lambda d, _k="winrar", _m="compress", _p=["files", "archive_path"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "winrar_extract": lambda d, _k="winrar", _m="extract", _p=["archive_path", "destination"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "winrar_list_contents": lambda d, _k="winrar", _m="list_contents", _p=["archive_path"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- AntivirusApp --
    "antivirus_get_status": lambda d, _k="antivirus", _m="get_status", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- BitLockerApp --
    "bitlocker_get_all_status": lambda d, _k="bitlocker", _m="get_all_status", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "bitlocker_get_status": lambda d, _k="bitlocker", _m="get_status", _p=["drive"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- FirewallApp --
    "firewall_disable": lambda d, _k="firewall", _m="disable", _p=["profile"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "firewall_enable": lambda d, _k="firewall", _m="enable", _p=["profile"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "firewall_get_status": lambda d, _k="firewall", _m="get_status", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "firewall_list_rules": lambda d, _k="firewall", _m="list_rules", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "firewall_open_console": lambda d, _k="firewall", _m="open_console", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- WindowsDefenderApp --
    "windows_defender_get_status": lambda d, _k="windows_defender", _m="get_status", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "windows_defender_open_security_center": lambda d, _k="windows_defender", _m="open_security_center", _p=[]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "windows_defender_run_quick_scan": lambda d, _k="windows_defender", _m="run_quick_scan", _p=[]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "windows_defender_update_definitions": lambda d, _k="windows_defender", _m="update_definitions", _p=[]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    # -- DiscordGamingApp --
    "discord_gaming_detect_running_games": lambda d, _k="discord_gaming", _m="detect_running_games", _p=[]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "discord_gaming_join_voice_channel": lambda d, _k="discord_gaming", _m="join_voice_channel", _p=[
        "server_id",
        "channel_id",
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "discord_gaming_open_and_detect": lambda d, _k="discord_gaming", _m="open_and_detect", _p=[]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- EpicGamesApp --
    "epic_games_launch_game": lambda d, _k="epic_games", _m="launch_game", _p=["app_name", "silent"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "epic_games_open_store": lambda d, _k="epic_games", _m="open_store", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    # -- SteamApp --
    "steam_launch_game": lambda d, _k="steam", _m="launch_game", _p=["app_id"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "steam_open_friends": lambda d, _k="steam", _m="open_friends", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "steam_open_library": lambda d, _k="steam", _m="open_library", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "steam_open_store_page": lambda d, _k="steam", _m="open_store_page", _p=["app_id"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- XboxApp --
    "xbox_open_app": lambda d, _k="xbox", _m="open_app", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "xbox_open_game_bar": lambda d, _k="xbox", _m="open_game_bar", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "xbox_screenshot": lambda d, _k="xbox", _m="screenshot", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "xbox_take_game_clip": lambda d, _k="xbox", _m="take_game_clip", _p=[]: getattr(_get(_k), _m)(**_pick(d, _p)),
}
