"""
Phase 7 browser-data tool registry (auto-generated)
=======================================================
Wires the NEW browser/* classes this phase adds (per-browser
downloads/cookies/bookmarks/history plus generic tab control and
cross-browser download management) into the AI tool-calling loop.

The browser/* classes from earlier phases (BookmarkManager,
HistoryAnalyzer, TabManager, DownloadsTools, CookieTools, FormFiller)
are already wired directly in core/executor.py - deliberately left
alone here to avoid duplicate/colliding tool names.

Generated by scripts/_generate_browser_tools.py - re-run that script
after adding/changing a method on one of TARGETS' classes.
"""

from typing import Dict


def _tool(name: str, description: str, properties: dict = None, required: list = None) -> dict:
    """Identical shape to ai/tools_schema.py's _tool() - duplicated on
    purpose to avoid a circular import (see ai/new_skills_tools.py)."""
    return {
        "type": "function",
        "function": {
            "name": name,
            "description": description,
            "parameters": {
                "type": "object",
                "properties": properties or {},
                "required": required or [],
            },
        },
    }


def _pick(d: dict, keys: list) -> dict:
    """Filter a raw tool-call args dict down to keys the method accepts,
    dropping missing/None entries so the method's own defaults apply."""
    return {k: d[k] for k in keys if k in d and d[k] is not None}


BROWSER_REGISTRY: Dict[str, str] = {
    "chrome_dl": "browser.chrome.downloads.ChromeDownloads",
    "chrome_cookies": "browser.chrome.cookies.ChromeCookies",
    "chrome_bookmarks": "browser.chrome.bookmarks.ChromeBookmarks",
    "chrome_history": "browser.chrome.history.ChromeHistory",
    "edge_dl": "browser.edge.downloads.EdgeDownloads",
    "firefox_dl": "browser.firefox.downloads.FirefoxDownloads",
    "gtab": "browser.automation.tab_manager.GenericTabManager",
    "download_mgr": "browser.automation.download_manager.DownloadManager",
}

_instances: Dict[str, object] = {}


def _get(key: str):
    if key in _instances:
        return _instances[key]
    module_path, class_name = BROWSER_REGISTRY[key].rsplit(".", 1)
    import importlib

    mod = importlib.import_module(module_path)
    obj = getattr(mod, class_name)()
    _instances[key] = obj
    return obj


BROWSER_TOOLS = [
    # ChromeDownloads (browser.chrome.downloads)
    _tool(
        "chrome_dl_clear_downloads",
        "ChromeDownloads: Delete files from Downloads. If older_than_days is set, only",
        {"older_than_days": {"type": "integer"}, "confirm": {"type": "boolean"}},
        [],
    ),
    _tool(
        "chrome_dl_download_history",
        "ChromeDownloads: Read recent download history (filename + source URL) straight",
        {"limit": {"type": "integer"}},
        [],
    ),
    _tool(
        "chrome_dl_list_downloads",
        "ChromeDownloads: List files in the Downloads folder, most recent first.",
        {"limit": {"type": "integer"}},
        [],
    ),
    _tool(
        "chrome_dl_open_download",
        "ChromeDownloads: Open a file from the Downloads folder with its default app.",
        {"filename": {"type": "string"}},
        ["filename"],
    ),
    _tool(
        "chrome_dl_search_downloads",
        "ChromeDownloads: Search Chrome's download history for a filename/URL substring.",
        {"query": {"type": "string"}, "limit": {"type": "integer"}},
        ["query"],
    ),
    # ChromeCookies (browser.chrome.cookies)
    _tool(
        "chrome_cookies_delete_cookies_for_domain",
        "ChromeCookies: Delete every stored cookie for a domain. Close Chrome first -",
        {"domain": {"type": "string"}, "confirm": {"type": "boolean"}},
        ["domain"],
    ),
    _tool(
        "chrome_cookies_get_cookie_value",
        "ChromeCookies (Read (decrypted) and delete cookies from Chrome's own cookie store.): get cookie value.",
        {"domain": {"type": "string"}, "cookie_name": {"type": "string"}},
        ["domain", "cookie_name"],
    ),
    _tool(
        "chrome_cookies_get_cookies",
        "ChromeCookies: All cookies (name/value/path/expiry) Chrome has stored for a domain.",
        {"domain": {"type": "string"}},
        ["domain"],
    ),
    # ChromeBookmarks (browser.chrome.bookmarks)
    _tool(
        "chrome_bookmarks_add_bookmark",
        "ChromeBookmarks: Close Chrome first - it rewrites the Bookmarks file from memory",
        {"name": {"type": "string"}, "url": {"type": "string"}, "folder": {"type": "string"}},
        ["name", "url"],
    ),
    _tool(
        "chrome_bookmarks_delete_bookmark",
        "ChromeBookmarks (List/search/add/delete bookmarks in Chrome.): delete bookmark.",
        {"name": {"type": "string"}},
        ["name"],
    ),
    _tool(
        "chrome_bookmarks_list_bookmarks",
        "ChromeBookmarks (List/search/add/delete bookmarks in Chrome.): list bookmarks.",
        {},
        [],
    ),
    _tool(
        "chrome_bookmarks_search_bookmarks",
        "ChromeBookmarks (List/search/add/delete bookmarks in Chrome.): search bookmarks.",
        {"query": {"type": "string"}},
        ["query"],
    ),
    # ChromeHistory (browser.chrome.history)
    _tool(
        "chrome_history_activity_by_hour",
        "ChromeHistory (Read Chrome browsing history, and delete individual URLs from it.): activity by hour.",
        {"days": {"type": "integer"}},
        [],
    ),
    _tool(
        "chrome_history_delete_url",
        "ChromeHistory: Delete every visit entry for one URL from Chrome's history.",
        {"url": {"type": "string"}, "confirm": {"type": "boolean"}},
        ["url"],
    ),
    _tool(
        "chrome_history_most_visited",
        "ChromeHistory (Read Chrome browsing history, and delete individual URLs from it.): most visited.",
        {"limit": {"type": "integer"}},
        [],
    ),
    _tool(
        "chrome_history_recent_history",
        "ChromeHistory (Read Chrome browsing history, and delete individual URLs from it.): recent history.",
        {"limit": {"type": "integer"}},
        [],
    ),
    _tool(
        "chrome_history_search_history",
        "ChromeHistory (Read Chrome browsing history, and delete individual URLs from it.): search history.",
        {"query": {"type": "string"}, "limit": {"type": "integer"}},
        ["query"],
    ),
    _tool(
        "chrome_history_top_domains",
        "ChromeHistory (Read Chrome browsing history, and delete individual URLs from it.): top domains.",
        {"limit": {"type": "integer"}, "days": {"type": "integer"}},
        [],
    ),
    # EdgeDownloads (browser.edge.downloads)
    _tool(
        "edge_dl_clear_downloads",
        "EdgeDownloads: Delete files from Downloads. Safety-gated: needs confirm=true.",
        {"older_than_days": {"type": "integer"}, "confirm": {"type": "boolean"}},
        [],
    ),
    _tool(
        "edge_dl_download_history",
        "EdgeDownloads: Read recent download history (filename + source URL) straight",
        {"limit": {"type": "integer"}},
        [],
    ),
    _tool(
        "edge_dl_list_downloads",
        "EdgeDownloads: List files in the Downloads folder, most recent first.",
        {"limit": {"type": "integer"}},
        [],
    ),
    _tool(
        "edge_dl_open_download",
        "EdgeDownloads: Open a file from the Downloads folder with its default app.",
        {"filename": {"type": "string"}},
        ["filename"],
    ),
    _tool(
        "edge_dl_search_downloads",
        "EdgeDownloads: Search Edge's download history for a filename/URL substring.",
        {"query": {"type": "string"}, "limit": {"type": "integer"}},
        ["query"],
    ),
    # FirefoxDownloads (browser.firefox.downloads)
    _tool(
        "firefox_dl_clear_downloads",
        "FirefoxDownloads: Delete files from Downloads. Safety-gated: needs confirm=true.",
        {"older_than_days": {"type": "integer"}, "confirm": {"type": "boolean"}},
        [],
    ),
    _tool(
        "firefox_dl_download_history",
        "FirefoxDownloads: Read recent download history (filename + source page URL) from",
        {"limit": {"type": "integer"}},
        [],
    ),
    _tool(
        "firefox_dl_list_downloads",
        "FirefoxDownloads: List files in the Downloads folder, most recent first.",
        {"limit": {"type": "integer"}},
        [],
    ),
    _tool(
        "firefox_dl_open_download",
        "FirefoxDownloads: Open a file from the Downloads folder with its default app.",
        {"filename": {"type": "string"}},
        ["filename"],
    ),
    _tool(
        "firefox_dl_search_downloads",
        "FirefoxDownloads: Search Firefox's download history for a filename/URL substring.",
        {"query": {"type": "string"}, "limit": {"type": "integer"}},
        ["query"],
    ),
    # GenericTabManager (browser.automation.tab_manager)
    _tool(
        "gtab_close_current_tab",
        "GenericTabManager (Keyboard-shortcut-driven tab control for whichever browser is active.): close current tab.",
        {"browser": {"type": "string"}},
        [],
    ),
    _tool(
        "gtab_duplicate_tab",
        "GenericTabManager: Alt+Shift+D duplicates the current tab in every supported",
        {"browser": {"type": "string"}},
        [],
    ),
    _tool(
        "gtab_go_to_tab",
        "GenericTabManager: Ctrl+1..8 jumps to that tab position; Ctrl+9 always jumps to",
        {"index": {"type": "integer"}, "browser": {"type": "string"}},
        ["index"],
    ),
    _tool(
        "gtab_mute_tab",
        "GenericTabManager: Chrome/Edge only: M toggles audio mute for the active tab.",
        {"browser": {"type": "string"}},
        [],
    ),
    _tool(
        "gtab_new_incognito_window",
        "GenericTabManager: Ctrl+Shift+N (Chrome/Edge incognito, Firefox private window - same shortcut).",
        {"browser": {"type": "string"}},
        [],
    ),
    _tool(
        "gtab_new_tab",
        "GenericTabManager (Keyboard-shortcut-driven tab control for whichever browser is active.): new tab.",
        {"url": {"type": "string"}, "browser": {"type": "string"}},
        [],
    ),
    _tool(
        "gtab_new_window",
        "GenericTabManager (Keyboard-shortcut-driven tab control for whichever browser is active.): new window.",
        {"browser": {"type": "string"}},
        [],
    ),
    _tool(
        "gtab_next_tab",
        "GenericTabManager (Keyboard-shortcut-driven tab control for whichever browser is active.): next tab.",
        {"browser": {"type": "string"}},
        [],
    ),
    _tool(
        "gtab_previous_tab",
        "GenericTabManager (Keyboard-shortcut-driven tab control for whichever browser is active.): previous tab.",
        {"browser": {"type": "string"}},
        [],
    ),
    _tool(
        "gtab_reopen_closed_tab",
        "GenericTabManager (Keyboard-shortcut-driven tab control for whichever browser is active.): reopen closed tab.",
        {"browser": {"type": "string"}},
        [],
    ),
    # DownloadManager (browser.automation.download_manager)
    _tool(
        "download_mgr_clear_all_downloads",
        "DownloadManager: Delete files from the shared Downloads folder. Safety-gated:",
        {"older_than_days": {"type": "integer"}, "confirm": {"type": "boolean"}},
        [],
    ),
    _tool(
        "download_mgr_get_all_download_history",
        "DownloadManager: Every browser's download history in one call, tagged by browser.",
        {"limit_per_browser": {"type": "integer"}},
        [],
    ),
    _tool(
        "download_mgr_get_latest_download",
        "DownloadManager: The single most recently modified file in the Downloads folder.",
        {},
        [],
    ),
    _tool(
        "download_mgr_list_downloads",
        "DownloadManager: List files in the shared Downloads folder (same folder for",
        {"limit": {"type": "integer"}},
        [],
    ),
    _tool(
        "download_mgr_organize_downloads",
        "DownloadManager: Sort files in Downloads into images/documents/archives/installers/",
        {"dry_run": {"type": "boolean"}},
        [],
    ),
    _tool(
        "download_mgr_wait_for_download",
        "DownloadManager: Poll the Downloads folder until a new file appears (optionally",
        {"timeout": {"type": "number"}, "name_contains": {"type": "string"}},
        [],
    ),
]

BROWSER_DIRECT_HANDLERS = {
    # -- ChromeDownloads --
    "chrome_dl_clear_downloads": lambda d, _k="chrome_dl", _m="clear_downloads", _p=[
        "older_than_days",
        "confirm",
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "chrome_dl_download_history": lambda d, _k="chrome_dl", _m="download_history", _p=["limit"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "chrome_dl_list_downloads": lambda d, _k="chrome_dl", _m="list_downloads", _p=["limit"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "chrome_dl_open_download": lambda d, _k="chrome_dl", _m="open_download", _p=["filename"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "chrome_dl_search_downloads": lambda d, _k="chrome_dl", _m="search_downloads", _p=["query", "limit"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    # -- ChromeCookies --
    "chrome_cookies_delete_cookies_for_domain": lambda d, _k="chrome_cookies", _m="delete_cookies_for_domain", _p=[
        "domain",
        "confirm",
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "chrome_cookies_get_cookie_value": lambda d, _k="chrome_cookies", _m="get_cookie_value", _p=[
        "domain",
        "cookie_name",
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "chrome_cookies_get_cookies": lambda d, _k="chrome_cookies", _m="get_cookies", _p=["domain"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- ChromeBookmarks --
    "chrome_bookmarks_add_bookmark": lambda d, _k="chrome_bookmarks", _m="add_bookmark", _p=[
        "name",
        "url",
        "folder",
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "chrome_bookmarks_delete_bookmark": lambda d, _k="chrome_bookmarks", _m="delete_bookmark", _p=["name"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "chrome_bookmarks_list_bookmarks": lambda d, _k="chrome_bookmarks", _m="list_bookmarks", _p=[]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "chrome_bookmarks_search_bookmarks": lambda d, _k="chrome_bookmarks", _m="search_bookmarks", _p=["query"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    # -- ChromeHistory --
    "chrome_history_activity_by_hour": lambda d, _k="chrome_history", _m="activity_by_hour", _p=["days"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "chrome_history_delete_url": lambda d, _k="chrome_history", _m="delete_url", _p=["url", "confirm"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "chrome_history_most_visited": lambda d, _k="chrome_history", _m="most_visited", _p=["limit"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "chrome_history_recent_history": lambda d, _k="chrome_history", _m="recent_history", _p=["limit"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "chrome_history_search_history": lambda d, _k="chrome_history", _m="search_history", _p=["query", "limit"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "chrome_history_top_domains": lambda d, _k="chrome_history", _m="top_domains", _p=["limit", "days"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    # -- EdgeDownloads --
    "edge_dl_clear_downloads": lambda d, _k="edge_dl", _m="clear_downloads", _p=["older_than_days", "confirm"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "edge_dl_download_history": lambda d, _k="edge_dl", _m="download_history", _p=["limit"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "edge_dl_list_downloads": lambda d, _k="edge_dl", _m="list_downloads", _p=["limit"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "edge_dl_open_download": lambda d, _k="edge_dl", _m="open_download", _p=["filename"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "edge_dl_search_downloads": lambda d, _k="edge_dl", _m="search_downloads", _p=["query", "limit"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    # -- FirefoxDownloads --
    "firefox_dl_clear_downloads": lambda d, _k="firefox_dl", _m="clear_downloads", _p=[
        "older_than_days",
        "confirm",
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "firefox_dl_download_history": lambda d, _k="firefox_dl", _m="download_history", _p=["limit"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "firefox_dl_list_downloads": lambda d, _k="firefox_dl", _m="list_downloads", _p=["limit"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "firefox_dl_open_download": lambda d, _k="firefox_dl", _m="open_download", _p=["filename"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "firefox_dl_search_downloads": lambda d, _k="firefox_dl", _m="search_downloads", _p=["query", "limit"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    # -- GenericTabManager --
    "gtab_close_current_tab": lambda d, _k="gtab", _m="close_current_tab", _p=["browser"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "gtab_duplicate_tab": lambda d, _k="gtab", _m="duplicate_tab", _p=["browser"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "gtab_go_to_tab": lambda d, _k="gtab", _m="go_to_tab", _p=["index", "browser"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "gtab_mute_tab": lambda d, _k="gtab", _m="mute_tab", _p=["browser"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "gtab_new_incognito_window": lambda d, _k="gtab", _m="new_incognito_window", _p=["browser"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    "gtab_new_tab": lambda d, _k="gtab", _m="new_tab", _p=["url", "browser"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "gtab_new_window": lambda d, _k="gtab", _m="new_window", _p=["browser"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "gtab_next_tab": lambda d, _k="gtab", _m="next_tab", _p=["browser"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "gtab_previous_tab": lambda d, _k="gtab", _m="previous_tab", _p=["browser"]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "gtab_reopen_closed_tab": lambda d, _k="gtab", _m="reopen_closed_tab", _p=["browser"]: getattr(_get(_k), _m)(
        **_pick(d, _p)
    ),
    # -- DownloadManager --
    "download_mgr_clear_all_downloads": lambda d, _k="download_mgr", _m="clear_all_downloads", _p=[
        "older_than_days",
        "confirm",
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "download_mgr_get_all_download_history": lambda d, _k="download_mgr", _m="get_all_download_history", _p=[
        "limit_per_browser"
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
    "download_mgr_get_latest_download": lambda d, _k="download_mgr", _m="get_latest_download", _p=[]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "download_mgr_list_downloads": lambda d, _k="download_mgr", _m="list_downloads", _p=["limit"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "download_mgr_organize_downloads": lambda d, _k="download_mgr", _m="organize_downloads", _p=["dry_run"]: getattr(
        _get(_k), _m
    )(**_pick(d, _p)),
    "download_mgr_wait_for_download": lambda d, _k="download_mgr", _m="wait_for_download", _p=[
        "timeout",
        "name_contains",
    ]: getattr(_get(_k), _m)(**_pick(d, _p)),
}
