"""
One-off generator for ai/browser_tools.py (Phase 7 wiring).
Same approach as scripts/_generate_apps_tools.py, but for the new
browser/* classes this phase adds. Existing browser/* classes
(BookmarkManager, HistoryAnalyzer, TabManager, DownloadsTools, CookieTools,
FormFiller) are already wired directly in core/executor.py from earlier
phases and are deliberately left alone - this only wires the classes/
methods that are actually new. Run once; the output is committed as
regular source, not regenerated at import time.
"""

import importlib
import inspect
import os
import sys
import typing

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# (key, module_path, class_name) - key is the tool-name prefix, chosen to
# not collide with any existing tool name in core/executor.py.
TARGETS = [
    ("chrome_dl", "browser.chrome.downloads", "ChromeDownloads"),
    ("chrome_cookies", "browser.chrome.cookies", "ChromeCookies"),
    ("chrome_bookmarks", "browser.chrome.bookmarks", "ChromeBookmarks"),
    ("chrome_history", "browser.chrome.history", "ChromeHistory"),
    ("edge_dl", "browser.edge.downloads", "EdgeDownloads"),
    ("firefox_dl", "browser.firefox.downloads", "FirefoxDownloads"),
    ("gtab", "browser.automation.tab_manager", "GenericTabManager"),
    ("download_mgr", "browser.automation.download_manager", "DownloadManager"),
]


def json_type_for(annotation):
    if annotation is inspect._empty:
        return "string"
    origin = typing.get_origin(annotation)
    if origin is typing.Union:
        args = [a for a in typing.get_args(annotation) if a is not type(None)]
        if len(args) == 1:
            return json_type_for(args[0])
        return "string"
    if origin in (list, typing.List):
        return "array"
    if origin in (dict, typing.Dict):
        return "object"
    if annotation in (str,):
        return "string"
    if annotation in (int,):
        return "integer"
    if annotation in (float,):
        return "number"
    if annotation in (bool,):
        return "boolean"
    return "string"


def own_methods(cls):
    methods = []
    for name, val in vars(cls).items():
        if name.startswith("_"):
            continue
        if not inspect.isfunction(val):
            continue
        methods.append((name, val))
    return sorted(methods)


def build_tool_and_handler(key, class_name, method_name, func, class_doc):
    tool_name = f"{key}_{method_name}"
    sig = inspect.signature(func)
    properties = {}
    required = []
    pick_keys = []
    for pname, param in sig.parameters.items():
        if pname == "self":
            continue
        if param.kind in (inspect.Parameter.VAR_POSITIONAL, inspect.Parameter.VAR_KEYWORD):
            continue
        properties[pname] = {"type": json_type_for(param.annotation)}
        pick_keys.append(pname)
        if param.default is inspect._empty:
            required.append(pname)
    own_doc = inspect.getdoc(func)
    humanized = method_name.replace("_", " ")
    if own_doc:
        description = f"{class_name}: {own_doc.splitlines()[0]}"
    elif class_doc:
        description = f"{class_name} ({class_doc.splitlines()[0]}): {humanized}."
    else:
        description = f"{class_name}: {humanized}."
    return tool_name, properties, required, pick_keys, description


def main():
    lines = []
    lines.append('"""')
    lines.append("Phase 7 browser-data tool registry (auto-generated)")
    lines.append("=======================================================")
    lines.append("Wires the NEW browser/* classes this phase adds (per-browser")
    lines.append("downloads/cookies/bookmarks/history plus generic tab control and")
    lines.append("cross-browser download management) into the AI tool-calling loop.")
    lines.append("")
    lines.append("The browser/* classes from earlier phases (BookmarkManager,")
    lines.append("HistoryAnalyzer, TabManager, DownloadsTools, CookieTools, FormFiller)")
    lines.append("are already wired directly in core/executor.py - deliberately left")
    lines.append("alone here to avoid duplicate/colliding tool names.")
    lines.append("")
    lines.append("Generated by scripts/_generate_browser_tools.py - re-run that script")
    lines.append("after adding/changing a method on one of TARGETS' classes.")
    lines.append('"""')
    lines.append("from typing import Dict")
    lines.append("")
    lines.append("")
    lines.append("def _tool(name: str, description: str, properties: dict = None, required: list = None) -> dict:")
    lines.append('    """Identical shape to ai/tools_schema.py\'s _tool() - duplicated on')
    lines.append('    purpose to avoid a circular import (see ai/new_skills_tools.py)."""')
    lines.append("    return {")
    lines.append('        "type": "function",')
    lines.append('        "function": {')
    lines.append('            "name": name,')
    lines.append('            "description": description,')
    lines.append('            "parameters": {')
    lines.append('                "type": "object",')
    lines.append('                "properties": properties or {},')
    lines.append('                "required": required or [],')
    lines.append("            },")
    lines.append("        },")
    lines.append("    }")
    lines.append("")
    lines.append("")
    lines.append("def _pick(d: dict, keys: list) -> dict:")
    lines.append('    """Filter a raw tool-call args dict down to keys the method accepts,')
    lines.append('    dropping missing/None entries so the method\'s own defaults apply."""')
    lines.append("    return {k: d[k] for k in keys if k in d and d[k] is not None}")
    lines.append("")
    lines.append("")
    lines.append("BROWSER_REGISTRY: Dict[str, str] = {")
    for key, module_path, class_name in TARGETS:
        lines.append(f'    "{key}": "{module_path}.{class_name}",')
    lines.append("}")
    lines.append("")
    lines.append("_instances: Dict[str, object] = {}")
    lines.append("")
    lines.append("")
    lines.append("def _get(key: str):")
    lines.append("    if key in _instances:")
    lines.append("        return _instances[key]")
    lines.append('    module_path, class_name = BROWSER_REGISTRY[key].rsplit(".", 1)')
    lines.append("    import importlib")
    lines.append("    mod = importlib.import_module(module_path)")
    lines.append("    obj = getattr(mod, class_name)()")
    lines.append("    _instances[key] = obj")
    lines.append("    return obj")
    lines.append("")
    lines.append("")
    lines.append("BROWSER_TOOLS = [")

    handler_lines = ["BROWSER_DIRECT_HANDLERS = {"]
    seen = set()
    for key, module_path, class_name in TARGETS:
        mod = importlib.import_module(module_path)
        cls = getattr(mod, class_name)
        class_doc = inspect.getdoc(cls)
        methods = own_methods(cls)
        lines.append(f"    # {class_name} ({module_path})")
        handler_lines.append(f"    # -- {class_name} --")
        for method_name, func in methods:
            tool_name, properties, required, pick_keys, description = build_tool_and_handler(
                key, class_name, method_name, func, class_doc
            )
            if tool_name in seen:
                continue
            seen.add(tool_name)
            props_src = "{" + ", ".join(f'"{p}": {properties[p]!r}' for p in properties) + "}" if properties else "{}"
            req_src = repr(required)
            desc_escaped = description.replace('"', "'")
            lines.append(f'    _tool("{tool_name}", "{desc_escaped}", {props_src}, {req_src}),')
            keys_src = repr(pick_keys)
            handler_lines.append(
                f'    "{tool_name}": lambda d, _k="{key}", _m="{method_name}", _p={keys_src}: '
                f"getattr(_get(_k), _m)(**_pick(d, _p)),"
            )
        lines.append("")
    lines.append("]")
    handler_lines.append("}")

    out = "\n".join(lines) + "\n\n" + "\n".join(handler_lines) + "\n"
    with open("ai/browser_tools.py", "w") as f:
        f.write(out)
    print(f"Generated ai/browser_tools.py: {len(TARGETS)} classes, {len(seen)} tools")


if __name__ == "__main__":
    main()
