"""
One-off generator for ai/apps_tools.py (Phase 6 wiring).
Introspects every concrete App class under apps/*, and emits a tool
schema + direct-handler entry for every method the subclass itself
defines (own __dict__, not inherited from BaseApp) - i.e. exactly the
distinctive automation each app adds on top of the common
open/close/focus/is_running surface, which is instead exposed generically
via app_open/app_close/app_focus/app_is_running (see the hand-written
header of the generated file). Run once; the output is committed as
regular source, not regenerated at import time.
"""

import importlib
import inspect
import os
import sys
import typing

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

CATEGORY_DIRS = [
    "browsers",
    "office",
    "communication",
    "media",
    "design",
    "development",
    "cloud",
    "system",
    "utilities",
    "security",
    "gaming",
]

SKIP_MODULES = {"apps.base_app", "apps.cloud._sync_folder_base"}


def discover():
    """Returns list of (key, category, module_path, class_name, cls)."""
    found = []
    for category in CATEGORY_DIRS:
        pkg_dir = os.path.join("apps", category)
        for fname in sorted(os.listdir(pkg_dir)):
            if not fname.endswith(".py") or fname == "__init__.py":
                continue
            stem = fname[:-3]
            module_path = f"apps.{category}.{stem}"
            if module_path in SKIP_MODULES:
                continue
            mod = importlib.import_module(module_path)
            for name, obj in vars(mod).items():
                if inspect.isclass(obj) and obj.__module__ == module_path and name.endswith("App"):
                    found.append((stem, category, module_path, name, obj))
    return found


def json_type_for(annotation):
    """Best-effort Python type annotation -> JSON schema type."""
    if annotation is inspect._empty:
        return "string"
    origin = typing.get_origin(annotation)
    if origin is typing.Union:
        args = [a for a in typing.get_args(annotation) if a is not type(None)]
        if len(args) == 1:
            return json_type_for(args[0])
        return "string"
    if origin in (list, typing.List):
        return "array"
    if origin in (dict, typing.Dict):
        return "object"
    if annotation in (str,):
        return "string"
    if annotation in (int,):
        return "integer"
    if annotation in (float,):
        return "number"
    if annotation in (bool,):
        return "boolean"
    return "string"


def own_methods(cls):
    """Public methods defined directly on cls (own __dict__), not inherited."""
    methods = []
    for name, val in vars(cls).items():
        if name.startswith("_"):
            continue
        if not inspect.isfunction(val):
            continue
        methods.append((name, val))
    return sorted(methods)


def build_tool_and_handler(key, class_name, method_name, func, class_doc):
    tool_name = f"{key}_{method_name}"
    sig = inspect.signature(func)
    properties = {}
    required = []
    pick_keys = []
    for pname, param in sig.parameters.items():
        if pname == "self":
            continue
        if param.kind in (inspect.Parameter.VAR_POSITIONAL, inspect.Parameter.VAR_KEYWORD):
            continue
        properties[pname] = {"type": json_type_for(param.annotation)}
        pick_keys.append(pname)
        if param.default is inspect._empty:
            required.append(pname)
    own_doc = inspect.getdoc(func)
    humanized = method_name.replace("_", " ")
    app_label = class_name[:-3] if class_name.endswith("App") else class_name  # drop trailing "App"
    if own_doc:
        description = f"{app_label}: {own_doc.splitlines()[0]}"
    elif class_doc:
        description = f"{app_label} ({class_doc.splitlines()[0]}): {humanized}."
    else:
        description = f"{app_label}: {humanized}."
    return tool_name, properties, required, pick_keys, description


def main():
    apps_found = discover()
    lines = []
    lines.append('"""')
    lines.append("Phase 6 app-automation tool registry (auto-generated)")
    lines.append("=========================================================")
    lines.append("Wires every apps/* automation class into the AI tool-calling loop,")
    lines.append("mirroring ai/new_skills_tools.py's pattern: lazy singletons + a flat")
    lines.append("APPS_TOOLS / APPS_DIRECT_HANDLERS pair merged at the bottom of")
    lines.append("ai/tools_schema.py and ai/tool_runtime.py.")
    lines.append("")
    lines.append("Generated by scripts/_generate_apps_tools.py - re-run that script")
    lines.append("after adding/changing methods on an apps/* class rather than editing")
    lines.append("the per-app tool entries below by hand.")
    lines.append('"""')
    lines.append("from typing import Dict")
    lines.append("")
    lines.append("")
    lines.append("def _tool(name: str, description: str, properties: dict = None, required: list = None) -> dict:")
    lines.append('    """Identical shape to ai/tools_schema.py\'s _tool() - duplicated on')
    lines.append("    purpose (see ai/new_skills_tools.py's docstring for why: avoids a")
    lines.append('    circular import since tools_schema.py imports *from* this module)."""')
    lines.append("    return {")
    lines.append('        "type": "function",')
    lines.append('        "function": {')
    lines.append('            "name": name,')
    lines.append('            "description": description,')
    lines.append('            "parameters": {')
    lines.append('                "type": "object",')
    lines.append('                "properties": properties or {},')
    lines.append('                "required": required or [],')
    lines.append("            },")
    lines.append("        },")
    lines.append("    }")
    lines.append("")
    lines.append("")
    lines.append("def _pick(d: dict, keys: list) -> dict:")
    lines.append('    """Filter a raw tool-call args dict down to the keys a method')
    lines.append("    accepts, dropping missing/None entries so the method's own")
    lines.append('    defaults apply."""')
    lines.append("    return {k: d[k] for k in keys if k in d and d[k] is not None}")
    lines.append("")
    lines.append("")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# App registry - every apps/* class, keyed by its filename stem. Also used")
    lines.append("# by the four generic app_open/app_close/app_focus/app_is_running tools.")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("APP_REGISTRY: Dict[str, str] = {")
    for key, category, module_path, class_name, cls in apps_found:
        lines.append(f'    "{key}": "{module_path}.{class_name}",')
    lines.append("}")
    lines.append("")
    lines.append("_instances: Dict[str, object] = {}")
    lines.append("")
    lines.append("")
    lines.append("def _get(key: str):")
    lines.append("    if key in _instances:")
    lines.append("        return _instances[key]")
    lines.append("    if key not in APP_REGISTRY:")
    lines.append("        raise ValueError(f\"Unknown app '{key}'. Known: {sorted(APP_REGISTRY)}\")")
    lines.append('    module_path, class_name = APP_REGISTRY[key].rsplit(".", 1)')
    lines.append("    import importlib")
    lines.append("    mod = importlib.import_module(module_path)")
    lines.append("    obj = getattr(mod, class_name)()")
    lines.append("    _instances[key] = obj")
    lines.append("    return obj")
    lines.append("")
    lines.append("")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# Generic lifecycle tools (cover BaseApp's open/close/focus/is_running for")
    lines.append("# every app via one tool each, instead of duplicating 4 tools x 61 apps).")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("APPS_TOOLS = [")
    lines.append('    _tool("app_open", "Launch an installed desktop/web app by key (see list_available_apps).",')
    lines.append(
        '          {"app": {"type": "string", "description": "App key, e.g. \'chrome\', \'spotify\', \'vscode\'"}}, ["app"]),'
    )
    lines.append('    _tool("app_close", "Close a running app by key.",')
    lines.append('          {"app": {"type": "string"}}, ["app"]),')
    lines.append('    _tool("app_focus", "Bring an already-open app\'s window to the foreground.",')
    lines.append('          {"app": {"type": "string"}}, ["app"]),')
    lines.append('    _tool("app_is_running", "Check whether an app is currently running.",')
    lines.append('          {"app": {"type": "string"}}, ["app"]),')
    lines.append(
        '    _tool("list_available_apps", "List every app automation key Ultron knows, grouped by category."),'
    )
    lines.append("")
    lines.append("    # -- Per-app automations (auto-generated from each class's own methods) --")

    handler_lines = []
    handler_lines.append("APPS_DIRECT_HANDLERS = {")
    handler_lines.append('    "app_open": lambda d: _get(d.get("app", "")).open(),')
    handler_lines.append('    "app_close": lambda d: _get(d.get("app", "")).close(),')
    handler_lines.append('    "app_focus": lambda d: _get(d.get("app", "")).focus(),')
    handler_lines.append('    "app_is_running": lambda d: _get(d.get("app", "")).is_running(),')
    handler_lines.append('    "list_available_apps": lambda d: {"success": True, "apps": sorted(APP_REGISTRY)},')
    handler_lines.append("")

    seen_tool_names = set()
    for key, category, module_path, class_name, cls in apps_found:
        methods = own_methods(cls)
        if not methods:
            continue
        lines.append(f"    # {class_name} ({category}/{key}.py)")
        handler_lines.append(f"    # -- {class_name} --")
        class_doc = inspect.getdoc(cls)
        for method_name, func in methods:
            tool_name, properties, required, pick_keys, description = build_tool_and_handler(
                key, class_name, method_name, func, class_doc
            )
            if tool_name in seen_tool_names:
                continue
            seen_tool_names.add(tool_name)
            props_src = "{" + ", ".join(f'"{p}": {properties[p]!r}' for p in properties) + "}" if properties else "{}"
            req_src = repr(required)
            desc_escaped = description.replace('"', "'")
            lines.append(f'    _tool("{tool_name}", "{desc_escaped}", {props_src}, {req_src}),')
            keys_src = repr(pick_keys)
            handler_lines.append(
                f'    "{tool_name}": lambda d, _k="{key}", _m="{method_name}", _p={keys_src}: '
                f"getattr(_get(_k), _m)(**_pick(d, _p)),"
            )
        lines.append("")

    lines.append("]")
    lines.append("")
    handler_lines.append("}")

    out = "\n".join(lines) + "\n\n" + "\n".join(handler_lines) + "\n"
    with open("ai/apps_tools.py", "w") as f:
        f.write(out)
    print(
        f"Generated ai/apps_tools.py: {len(apps_found)} app classes, {len(seen_tool_names)} per-app tools + 5 generic"
    )


if __name__ == "__main__":
    main()
